-- Event System Pro PostgreSQL schema and seed data
-- Baseline for database: event_system_pro

-- Step 1: create database (as superuser)
--   psql -U postgres -c "CREATE DATABASE event_system_pro WITH ENCODING 'UTF8' TEMPLATE template0;"
--
-- Step 2: apply schema and seed data
--   psql -U postgres -d event_system_pro -f database/event-system-pro/evp_schema_postgresql.sql

\connect event_system_pro

SET client_encoding = 'UTF8';

DROP TABLE IF EXISTS tournament_bracket CASCADE;
DROP TABLE IF EXISTS attendee CASCADE;
DROP TABLE IF EXISTS user_preference CASCADE;
DROP TABLE IF EXISTS event_staff_pool CASCADE;
DROP TABLE IF EXISTS contest_heat CASCADE;
DROP TABLE IF EXISTS judging_panel CASCADE;
DROP TABLE IF EXISTS contest_entry CASCADE;
DROP TABLE IF EXISTS competitor CASCADE;
DROP TABLE IF EXISTS contest CASCADE;
DROP TABLE IF EXISTS contact CASCADE;
DROP TABLE IF EXISTS image CASCADE;
DROP TABLE IF EXISTS system_config CASCADE;
DROP TABLE IF EXISTS club CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "event" CASCADE;
DROP TABLE IF EXISTS event_group CASCADE;
DROP TABLE IF EXISTS static_list CASCADE;
DROP TABLE IF EXISTS governing_body CASCADE;
DROP TABLE IF EXISTS skill_level_lu CASCADE;
DROP TABLE IF EXISTS secret_question_lu CASCADE;
DROP TABLE IF EXISTS competitor_type_lu CASCADE;


-- Table: competitor_type_lu
CREATE TABLE IF NOT EXISTS competitor_type_lu (
  competitor_type_id INTEGER NOT NULL,
  description varchar(32) NOT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL DEFAULT 'c-agent',
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
PRIMARY KEY (competitor_type_id)
);

-- Table: secret_question_lu
CREATE TABLE IF NOT EXISTS secret_question_lu (
  secret_question_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  question varchar(256) NOT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL DEFAULT 'c-agent',
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
PRIMARY KEY (secret_question_id)
);

-- Table: skill_level_lu
CREATE TABLE IF NOT EXISTS skill_level_lu (
  skill_level_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  full_name varchar(32) DEFAULT NULL,
  abbr_name varchar(16) DEFAULT NULL,
  skill_level_group_id INTEGER DEFAULT NULL,
  ranking INTEGER DEFAULT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL DEFAULT 'c-agent',
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
PRIMARY KEY (skill_level_id)
);

-- Table: governing_body
CREATE TABLE IF NOT EXISTS governing_body (
  governing_body_code varchar(32) NOT NULL,
  long_name varchar(64) NOT NULL,
  short_name varchar(43) DEFAULT NULL,
  more_json json DEFAULT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL DEFAULT 'c-agent',
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
PRIMARY KEY (governing_body_code),
CONSTRAINT governing_body_code_uq UNIQUE (governing_body_code)
);

-- Table: static_list
CREATE TABLE IF NOT EXISTS static_list (
  list_code varchar(32) NOT NULL,
  governing_body_code varchar(32) NOT NULL,
  list_json json DEFAULT NULL,
  short_desc varchar(256) DEFAULT NULL,
PRIMARY KEY (list_code),
CONSTRAINT static_list_code_uq UNIQUE (list_code),
CONSTRAINT fk_static_list_governing_body FOREIGN KEY (governing_body_code) REFERENCES governing_body (governing_body_code)
);

-- Table: event_group
CREATE TABLE IF NOT EXISTS event_group (
  event_group_code varchar(64) NOT NULL DEFAULT '',
  full_name varchar(64) NOT NULL DEFAULT '',
  short_name varchar(32) DEFAULT NULL,
  directors_json json DEFAULT NULL,
  event_type_code varchar(32) DEFAULT NULL,
  more_json jsonb DEFAULT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(32) DEFAULT NULL,
  modified_date TIMESTAMPTZ DEFAULT NULL,
  modified_by varchar(32) DEFAULT NULL,
PRIMARY KEY (event_group_code)
);

-- Table: event
CREATE TABLE IF NOT EXISTS "event" (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  event_code varchar(64) NOT NULL,
  event_group_code varchar(64) DEFAULT NULL,
  name varchar(64) DEFAULT NULL,
  contact_user_id bigint DEFAULT NULL,
  host_club_id bigint DEFAULT NULL,
  country_code varchar(3) NOT NULL,
  state_or_province varchar(255) DEFAULT NULL,
  location_json varchar(4000) DEFAULT NULL,
  active BOOLEAN DEFAULT TRUE,
  number_of_days SMALLINT DEFAULT NULL,
  start_date TIMESTAMPTZ NULL DEFAULT NULL,
  end_date TIMESTAMPTZ NULL DEFAULT NULL,
  more_json jsonb DEFAULT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL,
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
PRIMARY KEY (event_code),
CONSTRAINT event_event_id_unique UNIQUE (event_id),
CONSTRAINT fk_event_event_group FOREIGN KEY (event_group_code) REFERENCES event_group (event_group_code)
);

CREATE OR REPLACE FUNCTION public.derive_event_code(
  p_event_group_code text,
  p_start_date timestamptz
)
RETURNS varchar(64)
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT left(
    upper(btrim(coalesce(nullif(p_event_group_code, ''), 'EVENT')))
    || '_'
    || coalesce(to_char(timezone('UTC', p_start_date), 'YYYY'), '0000')
    || '_'
    || coalesce(upper(to_char(timezone('UTC', p_start_date), 'Mon')), 'UNK'),
    64
  );
$$;

CREATE OR REPLACE FUNCTION public.event_assign_event_code()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_base_code varchar(64);
BEGIN
  IF NEW.event_code IS NOT NULL AND btrim(NEW.event_code) <> '' THEN
    NEW.event_code := left(upper(btrim(NEW.event_code)), 64);
    RETURN NEW;
  END IF;

  v_base_code := public.derive_event_code(NEW.event_group_code, NEW.start_date);

  IF NEW.event_id IS NOT NULL THEN
    NEW.event_code := left(v_base_code, 64);
    IF EXISTS (
      SELECT 1
      FROM public."event" AS e
      WHERE e.event_code = NEW.event_code
        AND e.event_id IS DISTINCT FROM NEW.event_id
    ) THEN
      NEW.event_code := left(v_base_code || '_' || NEW.event_id::text, 64);
    END IF;
  ELSE
    NEW.event_code := v_base_code;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_event_assign_event_code
  BEFORE INSERT OR UPDATE OF event_group_code, start_date, event_code
  ON public."event"
  FOR EACH ROW
  EXECUTE FUNCTION public.event_assign_event_code();

-- Table: club
CREATE TABLE IF NOT EXISTS club (
  club_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name varchar(64) DEFAULT NULL,
  nick_name varchar(128) NOT NULL,
  contact1_user_id bigint DEFAULT NULL,
  contact2_user_id bigint DEFAULT NULL,
  country_code varchar(3) NOT NULL,
  state_or_province varchar(255) NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL,
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
PRIMARY KEY (club_id)
);

-- Table: user
CREATE TABLE IF NOT EXISTS "user" (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  username varchar(64) NOT NULL UNIQUE,
  password_encrypted varchar(64) NOT NULL,
  name_json json DEFAULT NULL,
  email varchar(64) DEFAULT NULL,
  phone_numbers_json json DEFAULT NULL,
  social_media_json json DEFAULT NULL,
  volunteer_json json DEFAULT NULL,
  password_recovery_json json NOT NULL DEFAULT '{}'::json,
  additional_info_json json DEFAULT NULL,
  addresses_json json DEFAULT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL,
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
PRIMARY KEY (user_id)
);

-- Table: contact
CREATE TABLE IF NOT EXISTS contact (
  contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  location_id INTEGER DEFAULT NULL,
  first_name varchar(32) NOT NULL,
  last_name varchar(32) DEFAULT NULL,
  middle_initial varchar(16) DEFAULT NULL,
  name_prefix varchar(8) DEFAULT NULL,
  name_suffix varchar(8) DEFAULT NULL,
  primary_phone_area_code SMALLINT DEFAULT NULL,
  primary_phone_rest INTEGER DEFAULT NULL,
  secondary_phone_area_code SMALLINT DEFAULT NULL,
  secondary_phone_rest INTEGER DEFAULT NULL,
  email1 varchar(64) DEFAULT NULL,
  email2 varchar(64) DEFAULT NULL,
  social_media_1 varchar(64) DEFAULT NULL,
  social_media_2 varchar(64) DEFAULT NULL,
  url1 varchar(256) DEFAULT NULL,
  url2 varchar(256) DEFAULT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL DEFAULT 'c-agent',
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
PRIMARY KEY (contact_id)
);

-- Table: image
CREATE TABLE IF NOT EXISTS image (
  image_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name varchar(64) DEFAULT '',
  description varchar(64) DEFAULT '',
  source varchar(64) DEFAULT NULL,
  image BYTEA,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL DEFAULT 'c-agent',
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
PRIMARY KEY (image_id)
);

-- Table: system_config
CREATE TABLE IF NOT EXISTS system_config (
  system_config_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  label varchar(64) DEFAULT NULL,
  value JSONB DEFAULT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_by varchar(128) DEFAULT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_by varchar(128) DEFAULT NULL,
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
PRIMARY KEY (system_config_id)
);

-- Table: contest
CREATE TABLE IF NOT EXISTS contest (
  contest_id bigint NOT NULL,
  event_id bigint DEFAULT NULL,
  competitors_json JSONB NOT NULL,
  results_json JSONB NOT NULL,
  age_division_id INTEGER DEFAULT NULL,
  created_by varchar(31) NOT NULL,
  created_date date NOT NULL,
  current_heat_id INTEGER DEFAULT NULL,
  current_heat_index INTEGER DEFAULT NULL,
  event_type_code varchar(32) NOT NULL,
  media_links_json varchar(255) DEFAULT NULL,
  is_active INTEGER NOT NULL,
  is_cancelled INTEGER DEFAULT NULL,
  staff_json varchar(1000) DEFAULT NULL,
  location_json varchar(1000) DEFAULT NULL,
  male_or_female varchar(1) DEFAULT NULL,
  modified_by varchar(31) NOT NULL,
  modified_date date NOT NULL,
  number_of_heats INTEGER DEFAULT NULL,
  original_end_time date DEFAULT NULL,
  original_start_time date NOT NULL,
  primary_contact_id INTEGER DEFAULT NULL,
  pushed_back_end_time date DEFAULT NULL,
  pushed_back_start_time date DEFAULT NULL,
PRIMARY KEY (contest_id),
CONSTRAINT contest_ibfk_1 FOREIGN KEY (event_id) REFERENCES "event" (event_id)
);
CREATE INDEX IF NOT EXISTS event_id ON contest (event_id);

-- Table: contest_entry
CREATE TABLE IF NOT EXISTS contest_entry (
  contest_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  governing_body_code varchar(32) NOT NULL,
  contest_id bigint NOT NULL,
  competitors_json json NOT NULL DEFAULT '[]'::json,
  name varchar(64) DEFAULT NULL,
  more_json json DEFAULT NULL,
  scratched boolean NOT NULL DEFAULT false,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL DEFAULT 'c-agent',
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
PRIMARY KEY (contest_entry_id),
CONSTRAINT contest_entry_fk_governing_body FOREIGN KEY (governing_body_code) REFERENCES governing_body (governing_body_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
CONSTRAINT contest_entry_fk_contest FOREIGN KEY (contest_id) REFERENCES contest (contest_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX IF NOT EXISTS contest_entry_fk_governing_body ON contest_entry (governing_body_code);
CREATE INDEX IF NOT EXISTS contest_entry_fk_contest ON contest_entry (contest_id);

-- Table: judging_panel
-- judges_json shape: [{"name": "...", "judge_id": <number|string>}]
CREATE TABLE IF NOT EXISTS judging_panel (
  judging_panel_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  event_id bigint NOT NULL,
  contest_id bigint NOT NULL,
  judges_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_by varchar(128) NOT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_by varchar(128) NULL DEFAULT NULL,
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
PRIMARY KEY (judging_panel_id),
CONSTRAINT judging_panel_fk_event FOREIGN KEY (event_id) REFERENCES "event" (event_id) ON DELETE RESTRICT,
CONSTRAINT judging_panel_fk_contest FOREIGN KEY (contest_id) REFERENCES contest (contest_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS judging_panel_fk_event ON judging_panel (event_id);
CREATE INDEX IF NOT EXISTS judging_panel_fk_contest ON judging_panel (contest_id);

-- Table: competitor
CREATE TABLE IF NOT EXISTS competitor (
  competitor_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  contest_id bigint NOT NULL,
  event_id bigint NOT NULL,
  user_id bigint DEFAULT NULL,
  first_name varchar(32) DEFAULT NULL,
  last_name varchar(32) DEFAULT NULL,
  gear_json varchar(255) DEFAULT NULL,
  competitor_type_id INTEGER DEFAULT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL DEFAULT 'c-agent',
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
PRIMARY KEY (competitor_id),
CONSTRAINT competitor_fk_contest FOREIGN KEY (contest_id) REFERENCES contest (contest_id) ON DELETE RESTRICT,
CONSTRAINT competitor_fk_event FOREIGN KEY (event_id) REFERENCES "event" (event_id) ON DELETE RESTRICT,
CONSTRAINT competitor_fk_user FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX IF NOT EXISTS fk_competitor_type ON competitor (competitor_type_id);
CREATE INDEX IF NOT EXISTS competitor_fk_contest ON competitor (contest_id);
CREATE INDEX IF NOT EXISTS competitor_fk_event ON competitor (event_id);
CREATE INDEX IF NOT EXISTS fk_competitor_user_id ON competitor (user_id);

-- Table: attendee
CREATE TABLE IF NOT EXISTS attendee (
  attendee_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id bigint NOT NULL,
  event_id bigint NOT NULL,
  contests_json json DEFAULT NULL,
  competitor_id bigint DEFAULT NULL,
  volunteer_json json DEFAULT NULL,
  staff_json json DEFAULT NULL,
  notes_json json DEFAULT NULL,
  external_accounts_json json DEFAULT NULL,
  more_json jsonb DEFAULT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL DEFAULT 'c-agent',
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
PRIMARY KEY (attendee_id),
CONSTRAINT attendee_fk_user FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
CONSTRAINT attendee_fk_event FOREIGN KEY (event_id) REFERENCES "event" (event_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
CONSTRAINT attendee_fk_competitor FOREIGN KEY (competitor_id) REFERENCES competitor (competitor_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX IF NOT EXISTS attendee_fk_user ON attendee (user_id);
CREATE INDEX IF NOT EXISTS attendee_fk_event ON attendee (event_id);
CREATE INDEX IF NOT EXISTS attendee_fk_competitor ON attendee (competitor_id);

-- Table: tournament_bracket
CREATE TABLE IF NOT EXISTS tournament_bracket (
  tournament_bracket_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  event_id bigint NOT NULL,
  governing_body_code varchar(32) NOT NULL,
  tournament_bracket_json json DEFAULT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL DEFAULT 'c-agent',
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
PRIMARY KEY (tournament_bracket_id),
CONSTRAINT tournament_bracket_fk_event FOREIGN KEY (event_id) REFERENCES "event" (event_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
CONSTRAINT tournament_bracket_fk_governing_body FOREIGN KEY (governing_body_code) REFERENCES governing_body (governing_body_code) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX IF NOT EXISTS tournament_bracket_fk_event ON tournament_bracket (event_id);
CREATE INDEX IF NOT EXISTS tournament_bracket_fk_governing_body ON tournament_bracket (governing_body_code);

-- Table: contest_heat
CREATE TABLE IF NOT EXISTS contest_heat (
  heat_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  event_id bigint NOT NULL,
  contest_id bigint NOT NULL,
  is_currently_being_run INTEGER DEFAULT NULL,
  original_start_time TIMESTAMPTZ DEFAULT NULL,
  original_end_time TIMESTAMPTZ DEFAULT NULL,
  pushed_back_start_time TIMESTAMPTZ DEFAULT NULL,
  pushed_back_end_time TIMESTAMPTZ DEFAULT NULL,
  heat_index INTEGER DEFAULT NULL,
  next_heat_id INTEGER DEFAULT NULL,
  judging_panel_id INTEGER DEFAULT NULL,
  all_judges_finished_scoring INTEGER DEFAULT NULL,
  num_judges_wanting_more INTEGER DEFAULT NULL,
  has_mixed_divisions INTEGER DEFAULT NULL,
  created_by varchar(128) NOT NULL,
  created_date varchar(128) NOT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
  modified_date varchar(128) NOT NULL,
PRIMARY KEY (heat_id),
CONSTRAINT heat_fk_contest FOREIGN KEY (contest_id) REFERENCES contest (contest_id),
CONSTRAINT heat_fk_event FOREIGN KEY (event_id) REFERENCES "event" (event_id)
);
CREATE INDEX IF NOT EXISTS heat_fk_contest ON contest_heat (contest_id);
CREATE INDEX IF NOT EXISTS heat_fk_event ON contest_heat (event_id);

-- Table: event_staff_pool
CREATE TABLE IF NOT EXISTS event_staff_pool (
  event_staff_pool_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  event_id bigint DEFAULT NULL,
  event_code varchar(64) DEFAULT NULL,
  event_group_code varchar(64) DEFAULT NULL,
  head_judges_json varchar(128) DEFAULT NULL,
  judges_json jsonb DEFAULT '[]'::jsonb,
  volunteers_json varchar(1000) DEFAULT NULL,
  additional_staff_pools_json json DEFAULT NULL,
  contact_id INTEGER DEFAULT NULL,
  is_active INTEGER DEFAULT '1',
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(32) NOT NULL,
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(32) NULL DEFAULT NULL,
PRIMARY KEY (event_staff_pool_id),
CONSTRAINT event_staff_pool_fk_event FOREIGN KEY (event_id) REFERENCES "event" (event_id) ON DELETE RESTRICT,
CONSTRAINT event_staff_pool_fk_event_code FOREIGN KEY (event_code) REFERENCES "event" (event_code) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX IF NOT EXISTS fk_staff_contact_id ON event_staff_pool (contact_id);
CREATE INDEX IF NOT EXISTS fk_staff_group_code ON event_staff_pool (event_group_code);
CREATE INDEX IF NOT EXISTS event_staff_pool_fk_event ON event_staff_pool (event_id);
CREATE INDEX IF NOT EXISTS event_staff_pool_fk_event_code ON event_staff_pool (event_code);

-- Table: user_preference
CREATE TABLE IF NOT EXISTS user_preference (
  user_preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id bigint DEFAULT NULL,
  label varchar(64) DEFAULT NULL,
  value varchar(256) DEFAULT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_by varchar(128) DEFAULT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_by varchar(128) DEFAULT NULL,
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
PRIMARY KEY (user_preference_id),
CONSTRAINT user_preference_ibfk_1 FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX IF NOT EXISTS fk_up_user_id ON user_preference (user_id);

-- Seed data (legacy event groups / events; reference static_list rows are in baseline_reference_data.sql)

INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_ARMAGEDDON', 'Armageddon', 'Armageddon', '2021-04-04 06:16:45', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_AWAKENING', 'Awakening', 'Awakening', '2021-04-04 06:16:45', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_BATTLEGROUND', 'Battleground', 'Battleground', '2021-04-04 06:16:45', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_BATTLE_OF_CHAMPIONS', 'Battle of Champions', 'Battle of Champions', '2021-04-04 06:16:45', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_BEAST_COAST_BRAWL', 'Beast Coast Brawl', 'Beast Coast Brawl', '2021-04-04 06:16:45', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_CROSSROADS', 'Crossroads', 'Crossroads', '2021-04-04 06:16:45', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_CRUSHXOTICA', 'CrushXotica', 'CrushXotica', '2021-04-04 06:16:45', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_DARKWATCH', 'Darkwatch Championship Series', 'Darkwatch', '2021-04-04 06:16:45', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_FLORIDA_CUP', 'Florida Cup', 'Florida Cup', '2009-05-31 20:44:39', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_MEXICO_OPEN', 'Mexico Open', 'Mexico Open', '2009-05-31 20:44:39', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_RAGNAROK', 'Ragnarok', 'Ragnarok', '2021-04-04 06:16:45', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_RESOLUTION', 'Resolution Championship Series', 'Resolution', '2021-04-04 06:16:45', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_SOUTHERN_CALIFORNIA', 'Southern California Tournament', 'Southern California', '2021-04-04 06:16:45', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_STEAMPUNK', 'Steampunk Invitational', 'Steampunk Invitational', '2021-04-04 06:16:45', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_SUNCRUSHER', 'Suncrusher', 'Suncrusher', '2021-04-04 06:16:45', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_UNDERGROUND', 'Underground Fight Series', 'Underground', '2021-04-04 06:16:45', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_WIZARD_WORLD_CHICAGO', 'Wizard World Chicago', 'Wizard World Chicago', '2021-04-04 06:16:45', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_WIZARD_WORLD_COLUMBUS', 'Wizard World Columbus', 'Wizard World Columbus', '2021-04-04 06:16:45', 'ceg');
INSERT INTO event_group (event_group_code, full_name, short_name, created_date, created_by) VALUES ('TSL_WORLDS', 'TSL World Championshops', 'TSL Worlds', '2021-04-04 06:16:45', 'ceg');
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('1', 'TSL_ARMAGEDDON', 'Armageddon I ', NULL, NULL, 'USA', 'MN', '{}', TRUE, NULL, '2017-03-31 00:00:01', '2017-03-31 11:59:01', NULL, '2021-04-04 12:07:36', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('2', 'TSL_ARMAGEDDON', 'Armageddon II', NULL, NULL, 'USA', 'MN', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:19:09', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('3', 'TSL_ARMAGEDDON', 'Armageddon III', NULL, NULL, 'USA', 'MN', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:19:09', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('4', 'TSL_AWAKENING', 'Awakening I', NULL, NULL, 'USA', 'MN', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:19:09', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('5', 'TSL_BATTLEGROUND', 'Battleground I', NULL, NULL, 'USA', 'MN', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:45:42', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('6', 'TSL_BATTLEGROUND', 'Battleground II', NULL, NULL, 'USA', 'MN', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:45:42', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('7', 'TSL_BATTLE_OF_CHAMPIONS', 'Battle of Champions I ', NULL, NULL, 'USA', 'MN', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:45:42', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('8', 'TSL_BATTLE_OF_CHAMPIONS', 'Battle of Champions II', NULL, NULL, 'USA', 'MN', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:45:42', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('9', 'TSL_BATTLE_OF_CHAMPIONS', 'Battle of Champions III', NULL, NULL, 'USA', 'MN', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:45:42', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('10', 'TSL_BEAST_COAST_BRAWL', 'Beast Coast Brawl I', NULL, NULL, 'USA', 'MD', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:45:42', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('11', 'TSL_BEAST_COAST_BRAWL', 'Beast Coast Brawl II', NULL, NULL, 'USA', 'MD', '{}', FALSE, NULL, NULL, NULL, NULL, '2021-04-04 11:45:42', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('12', 'TSL_CROSSROADS', 'Crossroads', NULL, NULL, 'USA', 'OH', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:09:29', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('13', 'TSL_CROSSROADS', 'Crossroads II', NULL, NULL, 'USA', 'OH', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:09:29', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('14', 'TSL_CRUSHXOTICA', 'CrushXotica I', NULL, NULL, 'USA', 'FL', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:09:29', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('15', 'TSL_CRUSHXOTICA', 'CrushXotica II', NULL, NULL, 'USA', 'FL', '{}', FALSE, NULL, NULL, NULL, NULL, '2021-04-04 11:09:29', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('16', 'TSL_DARKWATCH', 'Darkwatch I', NULL, NULL, 'USA', 'CA', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:41:06', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('17', 'TSL_DARKWATCH', 'Darkwatch II', NULL, NULL, 'USA', 'CA', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:41:06', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('18', 'TSL_DARKWATCH', 'Darkwatch III', NULL, NULL, 'USA', 'CA', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:41:06', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('19', 'TSL_DARKWATCH', 'Darkwatch IV', NULL, NULL, 'USA', 'CA', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:41:06', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('20', 'TSL_DARKWATCH', 'Darkwatch V', NULL, NULL, 'USA', 'CA', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:41:06', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('21', 'TSL_DARKWATCH', 'Darkwatch VI', NULL, NULL, 'USA', 'CA', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:41:06', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('22', 'TSL_FLORIDA_CUP', 'Florida Cup', NULL, NULL, 'USA', 'FL', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:41:06', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('23', 'TSL_MEXICO_OPEN', 'Mexico Open', NULL, NULL, 'MEX', '', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:41:06', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('24', 'TSL_RAGNAROK', 'Ragnarok', NULL, NULL, 'USA', 'MN', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:33:15', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('25', 'TSL_RESOLUTION', 'Resolution I', NULL, NULL, 'USA', 'MN', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:42:39', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('26', 'TSL_RESOLUTION', 'Resolution II', NULL, NULL, 'USA', 'MN', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:41:52', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('27', 'TSL_RESOLUTION', 'Resolution III', NULL, NULL, 'USA', 'MN', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:41:52', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('28', 'TSL_RESOLUTION', 'Resolution IV', NULL, NULL, 'USA', 'MN', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:41:52', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('29', 'TSL_SOUTHERN_CALIFORNIA', 'Southern California 1', NULL, NULL, 'USA', 'CA', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:47:20', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('30', 'TSL_SOUTHERN_CALIFORNIA', 'Southern California 2', NULL, NULL, 'USA', 'CA', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:47:20', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('31', 'TSL_STEAMPUNK', 'Steampunk Invitational 1', NULL, NULL, 'USA', 'CA', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:49:10', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('32', 'TSL_STEAMPUNK', 'Steampunk Invitational 2', NULL, NULL, 'USA', 'CA', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:49:10', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('33', 'TSL_STEAMPUNK', 'Steampunk Invitational 3', NULL, NULL, 'USA', 'CA', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:49:10', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('34', 'TSL_SUNCRUSHER', 'Suncrusher I', NULL, NULL, 'USA', 'FL', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:41:06', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('35', 'TSL_SUNCRUSHER', 'Suncrusher II', NULL, NULL, 'USA', 'FL', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:41:06', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('36', 'TSL_SUNCRUSHER', 'Suncrusher III', NULL, NULL, 'USA', 'FL', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:41:06', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('37', 'TSL_UNDERGROUND', 'Underground I', NULL, NULL, 'USA', '', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:41:06', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('38', 'TSL_UNDERGROUND', 'Underground 2 ', NULL, NULL, 'USA', '', '{}', TRUE, NULL, NULL, NULL, NULL, '2021-04-04 11:41:06', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('39', 'TSL_UNDERGROUND', 'Underground 3', NULL, NULL, 'USA', '', '{}', FALSE, NULL, NULL, NULL, NULL, '2021-04-04 11:52:01', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('40', 'TSL_WIZARD_WORLD_CHICAGO', 'Wizard World Chicago 2017', NULL, NULL, 'USA', 'IL', '{}', FALSE, NULL, NULL, NULL, NULL, '2021-04-04 11:52:01', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('42', 'TSL_WIZARD_WORLD_COLUMBUS', 'Wizard World Columbus 2017', NULL, NULL, 'USA', 'OH', '{}', FALSE, NULL, NULL, NULL, NULL, '2021-04-04 11:52:01', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('43', 'TSL_WORLDS', 'TSL World Championships I', NULL, NULL, 'USA', 'MN', '{}', FALSE, NULL, NULL, NULL, NULL, '2021-04-04 11:59:02', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('44', 'TSL_WORLDS', 'TSL World Championships II', NULL, NULL, 'USA', 'NV', '{}', FALSE, NULL, NULL, NULL, NULL, '2021-04-04 11:52:01', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('45', 'TSL_WORLDS', 'TSL World Championships III', NULL, NULL, 'USA', 'NV', '{}', FALSE, NULL, NULL, NULL, NULL, '2021-04-04 11:52:01', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('46', 'TSL_WORLDS', 'TSL World Championships IV', NULL, NULL, 'USA', 'NV', '{}', FALSE, NULL, NULL, NULL, NULL, '2021-04-04 11:52:01', 'ceg', NULL, NULL);
INSERT INTO "event" (event_id, event_group_code, name, contact_user_id, host_club_id, country_code, state_or_province, location_json, active, number_of_days, start_date, end_date, more_json, created_date, created_by, modified_date, modified_by) VALUES ('47', 'TSL_WORLDS', 'TSL World Championships V', NULL, NULL, 'USA', 'NV', '{}', FALSE, NULL, NULL, NULL, NULL, '2021-04-04 11:52:01', 'ceg', NULL, NULL);

-- Align identity sequences with seeded primary keys

SELECT setval(pg_get_serial_sequence('event', 'event_id'), COALESCE((SELECT MAX(event_id) FROM "event"), 1));