-- Forgot-password RPCs for PostgREST (dev: returns verification code in JSON).
-- Run: psql -U postgres -d event_system_pro -f database/migrations/008_forgot_password_rpc.sql

\connect event_system_pro

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.user_password_reset (
  reset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public."user" (user_id) ON DELETE CASCADE,
  code_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_password_reset_user_id
  ON public.user_password_reset (user_id);

CREATE INDEX IF NOT EXISTS idx_user_password_reset_active
  ON public.user_password_reset (user_id, expires_at)
  WHERE used_at IS NULL;

-- ---------------------------------------------------------------------------
-- Step 1: request code (email or username)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION api.forgot_password_request(identifier text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, api
AS $$
DECLARE
  v_user public."user"%ROWTYPE;
  v_code text;
  v_code_hash text;
BEGIN
  SELECT *
  INTO v_user
  FROM public."user" u
  WHERE lower(u.email) = lower(trim(identifier))
     OR lower(u.username) = lower(trim(identifier))
  ORDER BY u.user_id
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN json_build_object(
      'ok', true,
      'message', 'If an account exists for that email or username, a verification code has been sent.'
    );
  END IF;

  v_code := lpad((floor(random() * 1000000)::int)::text, 6, '0');
  v_code_hash := crypt(v_code, gen_salt('bf'));

  UPDATE public.user_password_reset
  SET used_at = NOW()
  WHERE user_id = v_user.user_id
    AND used_at IS NULL;

  INSERT INTO public.user_password_reset (user_id, code_hash, expires_at)
  VALUES (v_user.user_id, v_code_hash, NOW() + INTERVAL '15 minutes');

  RETURN json_build_object(
    'ok', true,
    'message', 'If an account exists for that email or username, a verification code has been sent.',
    'email', v_user.email,
    'dev_verification_code', v_code
  );
END;
$$;

-- ---------------------------------------------------------------------------
-- Step 2: verify code
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS api.forgot_password_verify(text, text);

CREATE OR REPLACE FUNCTION api.forgot_password_verify(p_email text, p_code text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, api
AS $$
DECLARE
  v_user_id bigint;
  v_reset public.user_password_reset%ROWTYPE;
BEGIN
  SELECT u.user_id
  INTO v_user_id
  FROM public."user" u
  WHERE lower(u.email) = lower(trim(p_email))
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN json_build_object('ok', false, 'message', 'Invalid verification code.');
  END IF;

  SELECT *
  INTO v_reset
  FROM public.user_password_reset r
  WHERE r.user_id = v_user_id
    AND r.used_at IS NULL
    AND r.expires_at > NOW()
  ORDER BY r.created_at DESC
  LIMIT 1;

  IF NOT FOUND OR crypt(trim(p_code), v_reset.code_hash) <> v_reset.code_hash THEN
    RETURN json_build_object('ok', false, 'message', 'Invalid or expired verification code.');
  END IF;

  RETURN json_build_object('ok', true, 'message', 'Verification code accepted.');
END;
$$;

-- ---------------------------------------------------------------------------
-- Step 3: set new password
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS api.forgot_password_complete(text, text, text);

CREATE OR REPLACE FUNCTION api.forgot_password_complete(
  p_email text,
  p_code text,
  p_new_password text
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, api
AS $$
DECLARE
  v_user_id bigint;
  v_reset public.user_password_reset%ROWTYPE;
BEGIN
  IF p_new_password IS NULL OR length(trim(p_new_password)) < 8 THEN
    RETURN json_build_object(
      'ok', false,
      'message', 'Password must be at least 8 characters.'
    );
  END IF;

  SELECT u.user_id
  INTO v_user_id
  FROM public."user" u
  WHERE lower(u.email) = lower(trim(p_email))
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN json_build_object('ok', false, 'message', 'Invalid verification code.');
  END IF;

  SELECT *
  INTO v_reset
  FROM public.user_password_reset r
  WHERE r.user_id = v_user_id
    AND r.used_at IS NULL
    AND r.expires_at > NOW()
  ORDER BY r.created_at DESC
  LIMIT 1;

  IF NOT FOUND OR crypt(trim(p_code), v_reset.code_hash) <> v_reset.code_hash THEN
    RETURN json_build_object('ok', false, 'message', 'Invalid or expired verification code.');
  END IF;

  UPDATE public."user"
  SET password_encrypted = crypt(trim(p_new_password), gen_salt('bf')),
      updated_date = NOW(),
      updated_by = 'forgot_password'
  WHERE user_id = v_user_id;

  UPDATE public.user_password_reset
  SET used_at = NOW()
  WHERE reset_id = v_reset.reset_id;

  RETURN json_build_object('ok', true, 'message', 'Your password has been updated.');
END;
$$;

GRANT EXECUTE ON FUNCTION api.forgot_password_request(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION api.forgot_password_verify(text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION api.forgot_password_complete(text, text, text) TO anon, authenticated;
