-- Create judging_panel table.
-- Run as PostgreSQL superuser:
--   psql -U postgres -d event_system_pro -f database/migrations/016_judging_panel.sql
--
-- judges_json stores an array of judge objects, e.g.:
--   [{"name": "Jane Doe", "judge_id": 42}]

\connect event_system_pro

CREATE TABLE IF NOT EXISTS public.judging_panel (
  judging_panel_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  event_id bigint NOT NULL,
  contest_id bigint NOT NULL,
  judges_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_by varchar(128) NOT NULL,
  created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_modified_by varchar(128) NOT NULL,
  last_modified_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (judging_panel_id),
  CONSTRAINT judging_panel_fk_event FOREIGN KEY (event_id) REFERENCES public."event" (event_id) ON DELETE RESTRICT,
  CONSTRAINT judging_panel_fk_contest FOREIGN KEY (contest_id) REFERENCES public.contest (contest_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS judging_panel_fk_event ON public.judging_panel (event_id);
CREATE INDEX IF NOT EXISTS judging_panel_fk_contest ON public.judging_panel (contest_id);

CREATE OR REPLACE VIEW api.judging_panel AS
SELECT
  judging_panel_id,
  event_id,
  contest_id,
  judges_json,
  created_by,
  created_on,
  last_modified_by,
  last_modified_on
FROM public.judging_panel;

GRANT SELECT ON api.judging_panel TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.judging_panel TO anon, authenticated;
