-- Drop EVP_* prefixes: event_group_code derived from full_name (uppercase words).
-- Run as PostgreSQL superuser:
--   psql -U postgres -d event_system_pro -f database/migrations/028_event_group_code_from_full_name.sql

\connect event_system_pro

ALTER TABLE public."event"
  DROP CONSTRAINT IF EXISTS fk_event_event_group;

UPDATE public.event_group AS eg
SET event_group_code = m.new_code
FROM (
  VALUES
    ('EVP_DNC_BRINDLEWICK', 'BRINDLEWICK_CLASSIC'),
    ('EVP_DNC_LARKSPUR', 'LARKSPUR_OPEN'),
    ('EVP_DNC_MARIGLEN', 'MARIGLEN_INVITATIONAL'),
    ('EVP_DNC_SELWICK', 'SELWICK_CONGRESS'),
    ('EVP_DNC_THORNBAY', 'THORNBAY_COUPLES_CHAMPIONSHIP'),
    ('EVP_HEM_VELLGRIMM', 'VELLGRIMM_LONGSWORD_OPEN'),
    ('EVP_HEM_CINDERHOLT', 'CINDERHOLT_HEMA_SYMPOSIUM'),
    ('EVP_HEM_BRAMBLEGATE', 'BRAMBLEGATE_RAPIER_CUP'),
    ('EVP_HEM_MOSSWICK', 'MOSSWICK_STEEL_ACADEMY_OPEN'),
    ('EVP_HEM_HOLLOWFEN', 'HOLLOWFEN_BLADE_CONGRESS'),
    ('EVP_RCE_RIVETON', 'RIVETON_KART_GRAND_PRIX'),
    ('EVP_RCE_GLIMMERWICK', 'GLIMMERWICK_SPRINT_CUP'),
    ('EVP_RCE_DRAKEWELL', 'DRAKEWELL_OVAL_CLASSIC'),
    ('EVP_RCE_QUARRYLANE', 'QUARRYLANE_VELOCITY_200'),
    ('EVP_RCE_FOXMERE', 'FOXMERE_KART_INVITATIONAL'),
    ('EVP_RBT_ROBOT_RIOT', 'ROBOT_RIOT'),
    ('EVP_RBT_SERVO_SLAM', 'SERVO_SLAM'),
    ('EVP_RBT_RIVET_RUMBLE', 'RIVET_RUMBLE'),
    ('EVP_RBT_CIRCUIT_CARNAGE', 'CIRCUIT_CARNAGE'),
    ('EVP_RBT_GASKET_GAUNTLET', 'GASKET_GAUNTLET'),
    ('EVP_PLM_PORTLAND', 'PORTLAND_PLASMA_PRIX'),
    ('EVP_PLM_CHICAGO', 'CHICAGO_CHROME_CLASH'),
    ('EVP_PLM_STELLAR_SHOWDOWN', 'STELLAR_SHOWDOWN'),
    ('EVP_PLM_NEON_NEXUS', 'NEON_NEXUS'),
    ('EVP_PLM_MERIDIAN_MELEE', 'MERIDIAN_MELEE')
) AS m(old_code, new_code)
WHERE eg.event_group_code = m.old_code;

UPDATE public."event" AS e
SET event_group_code = m.new_code
FROM (
  VALUES
    ('EVP_DNC_BRINDLEWICK', 'BRINDLEWICK_CLASSIC'),
    ('EVP_DNC_LARKSPUR', 'LARKSPUR_OPEN'),
    ('EVP_DNC_MARIGLEN', 'MARIGLEN_INVITATIONAL'),
    ('EVP_DNC_SELWICK', 'SELWICK_CONGRESS'),
    ('EVP_DNC_THORNBAY', 'THORNBAY_COUPLES_CHAMPIONSHIP'),
    ('EVP_HEM_VELLGRIMM', 'VELLGRIMM_LONGSWORD_OPEN'),
    ('EVP_HEM_CINDERHOLT', 'CINDERHOLT_HEMA_SYMPOSIUM'),
    ('EVP_HEM_BRAMBLEGATE', 'BRAMBLEGATE_RAPIER_CUP'),
    ('EVP_HEM_MOSSWICK', 'MOSSWICK_STEEL_ACADEMY_OPEN'),
    ('EVP_HEM_HOLLOWFEN', 'HOLLOWFEN_BLADE_CONGRESS'),
    ('EVP_RCE_RIVETON', 'RIVETON_KART_GRAND_PRIX'),
    ('EVP_RCE_GLIMMERWICK', 'GLIMMERWICK_SPRINT_CUP'),
    ('EVP_RCE_DRAKEWELL', 'DRAKEWELL_OVAL_CLASSIC'),
    ('EVP_RCE_QUARRYLANE', 'QUARRYLANE_VELOCITY_200'),
    ('EVP_RCE_FOXMERE', 'FOXMERE_KART_INVITATIONAL'),
    ('EVP_RBT_ROBOT_RIOT', 'ROBOT_RIOT'),
    ('EVP_RBT_SERVO_SLAM', 'SERVO_SLAM'),
    ('EVP_RBT_RIVET_RUMBLE', 'RIVET_RUMBLE'),
    ('EVP_RBT_CIRCUIT_CARNAGE', 'CIRCUIT_CARNAGE'),
    ('EVP_RBT_GASKET_GAUNTLET', 'GASKET_GAUNTLET'),
    ('EVP_PLM_PORTLAND', 'PORTLAND_PLASMA_PRIX'),
    ('EVP_PLM_CHICAGO', 'CHICAGO_CHROME_CLASH'),
    ('EVP_PLM_STELLAR_SHOWDOWN', 'STELLAR_SHOWDOWN'),
    ('EVP_PLM_NEON_NEXUS', 'NEON_NEXUS'),
    ('EVP_PLM_MERIDIAN_MELEE', 'MERIDIAN_MELEE')
) AS m(old_code, new_code)
WHERE e.event_group_code = m.old_code;

UPDATE public.event_staff_pool AS s
SET event_group_code = m.new_code
FROM (
  VALUES
    ('EVP_DNC_BRINDLEWICK', 'BRINDLEWICK_CLASSIC'),
    ('EVP_DNC_LARKSPUR', 'LARKSPUR_OPEN'),
    ('EVP_DNC_MARIGLEN', 'MARIGLEN_INVITATIONAL'),
    ('EVP_DNC_SELWICK', 'SELWICK_CONGRESS'),
    ('EVP_DNC_THORNBAY', 'THORNBAY_COUPLES_CHAMPIONSHIP'),
    ('EVP_HEM_VELLGRIMM', 'VELLGRIMM_LONGSWORD_OPEN'),
    ('EVP_HEM_CINDERHOLT', 'CINDERHOLT_HEMA_SYMPOSIUM'),
    ('EVP_HEM_BRAMBLEGATE', 'BRAMBLEGATE_RAPIER_CUP'),
    ('EVP_HEM_MOSSWICK', 'MOSSWICK_STEEL_ACADEMY_OPEN'),
    ('EVP_HEM_HOLLOWFEN', 'HOLLOWFEN_BLADE_CONGRESS'),
    ('EVP_RCE_RIVETON', 'RIVETON_KART_GRAND_PRIX'),
    ('EVP_RCE_GLIMMERWICK', 'GLIMMERWICK_SPRINT_CUP'),
    ('EVP_RCE_DRAKEWELL', 'DRAKEWELL_OVAL_CLASSIC'),
    ('EVP_RCE_QUARRYLANE', 'QUARRYLANE_VELOCITY_200'),
    ('EVP_RCE_FOXMERE', 'FOXMERE_KART_INVITATIONAL'),
    ('EVP_RBT_ROBOT_RIOT', 'ROBOT_RIOT'),
    ('EVP_RBT_SERVO_SLAM', 'SERVO_SLAM'),
    ('EVP_RBT_RIVET_RUMBLE', 'RIVET_RUMBLE'),
    ('EVP_RBT_CIRCUIT_CARNAGE', 'CIRCUIT_CARNAGE'),
    ('EVP_RBT_GASKET_GAUNTLET', 'GASKET_GAUNTLET'),
    ('EVP_PLM_PORTLAND', 'PORTLAND_PLASMA_PRIX'),
    ('EVP_PLM_CHICAGO', 'CHICAGO_CHROME_CLASH'),
    ('EVP_PLM_STELLAR_SHOWDOWN', 'STELLAR_SHOWDOWN'),
    ('EVP_PLM_NEON_NEXUS', 'NEON_NEXUS'),
    ('EVP_PLM_MERIDIAN_MELEE', 'MERIDIAN_MELEE')
) AS m(old_code, new_code)
WHERE s.event_group_code = m.old_code;

DELETE FROM public.event_group
WHERE event_group_code LIKE 'EVP\_%' ESCAPE '\';

ALTER TABLE public."event"
  ADD CONSTRAINT fk_event_event_group
  FOREIGN KEY (event_group_code)
  REFERENCES public.event_group (event_group_code);
