-- attendee: links a user to an event with optional competitor, volunteer, staff, and notes data.
-- Run as PostgreSQL superuser:
--   psql -U postgres -d event_system_pro -f database/migrations/040_attendee.sql

\connect event_system_pro

CREATE TABLE IF NOT EXISTS public.attendee (
  attendee_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id bigint NOT NULL,
  event_id bigint NOT NULL,
  contests_json json DEFAULT NULL,
  competitor_id bigint DEFAULT NULL,
  volunteer_json json DEFAULT NULL,
  staff_json json DEFAULT NULL,
  notes_json json DEFAULT NULL,
  external_accounts_json json DEFAULT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL DEFAULT 'c-agent',
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
  PRIMARY KEY (attendee_id),
  CONSTRAINT attendee_fk_user FOREIGN KEY (user_id) REFERENCES public."user" (user_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT attendee_fk_event FOREIGN KEY (event_id) REFERENCES public."event" (event_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT attendee_fk_competitor FOREIGN KEY (competitor_id) REFERENCES public.competitor (competitor_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX IF NOT EXISTS attendee_fk_user ON public.attendee (user_id);
CREATE INDEX IF NOT EXISTS attendee_fk_event ON public.attendee (event_id);
CREATE INDEX IF NOT EXISTS attendee_fk_competitor ON public.attendee (competitor_id);

CREATE OR REPLACE VIEW api.attendee AS
SELECT
  attendee_id,
  user_id,
  event_id,
  contests_json,
  competitor_id,
  volunteer_json,
  staff_json,
  notes_json,
  external_accounts_json,
  created_date,
  created_by,
  modified_date,
  modified_by
FROM public.attendee;

GRANT SELECT ON api.attendee TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.attendee TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON api.attendee TO anon, authenticated;

NOTIFY pgrst, 'reload schema';
