-- tournament_bracket: bracket data for an event scoped to a governing body.
-- Run: psql -U postgres -d event_system_pro -f database/migrations/054_tournament_bracket.sql

\connect event_system_pro

CREATE TABLE IF NOT EXISTS public.tournament_bracket (
  tournament_bracket_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  event_id bigint NOT NULL,
  governing_body_code varchar(32) NOT NULL,
  tournament_bracket_json json DEFAULT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL DEFAULT 'c-agent',
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
  PRIMARY KEY (tournament_bracket_id),
  CONSTRAINT tournament_bracket_fk_event FOREIGN KEY (event_id)
    REFERENCES public."event" (event_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT tournament_bracket_fk_governing_body FOREIGN KEY (governing_body_code)
    REFERENCES public.governing_body (governing_body_code) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX IF NOT EXISTS tournament_bracket_fk_event ON public.tournament_bracket (event_id);
CREATE INDEX IF NOT EXISTS tournament_bracket_fk_governing_body
  ON public.tournament_bracket (governing_body_code);

DROP TRIGGER IF EXISTS trg_set_modified_audit ON public.tournament_bracket;
CREATE TRIGGER trg_set_modified_audit
  BEFORE UPDATE ON public.tournament_bracket
  FOR EACH ROW
  EXECUTE FUNCTION public.set_row_modified_audit();

CREATE OR REPLACE VIEW api.tournament_bracket AS
SELECT
  tournament_bracket_id,
  event_id,
  governing_body_code,
  tournament_bracket_json,
  created_date,
  created_by,
  modified_date,
  modified_by
FROM public.tournament_bracket;

GRANT SELECT ON api.tournament_bracket TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.tournament_bracket TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON api.tournament_bracket TO anon, authenticated;

NOTIFY pgrst, 'reload schema';
