-- contest_entry: competitors registered for a contest under a governing body.
-- Run: psql -U postgres -d event_system_pro -f database/migrations/055_contest_entry.sql

\connect event_system_pro

CREATE TABLE IF NOT EXISTS public.contest_entry (
  contest_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  governing_body_code varchar(32) NOT NULL,
  contest_id bigint NOT NULL,
  competitors_json json NOT NULL DEFAULT '[]'::json,
  name varchar(64) DEFAULT NULL,
  more_json json DEFAULT NULL,
  scratched boolean NOT NULL DEFAULT false,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL DEFAULT 'c-agent',
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
  PRIMARY KEY (contest_entry_id),
  CONSTRAINT contest_entry_fk_governing_body FOREIGN KEY (governing_body_code)
    REFERENCES public.governing_body (governing_body_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT contest_entry_fk_contest FOREIGN KEY (contest_id)
    REFERENCES public.contest (contest_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX IF NOT EXISTS contest_entry_fk_governing_body ON public.contest_entry (governing_body_code);
CREATE INDEX IF NOT EXISTS contest_entry_fk_contest ON public.contest_entry (contest_id);

DROP TRIGGER IF EXISTS trg_set_modified_audit ON public.contest_entry;
CREATE TRIGGER trg_set_modified_audit
  BEFORE UPDATE ON public.contest_entry
  FOR EACH ROW
  EXECUTE FUNCTION public.set_row_modified_audit();

CREATE OR REPLACE VIEW api.contest_entry AS
SELECT
  contest_entry_id,
  governing_body_code,
  contest_id,
  competitors_json,
  name,
  more_json,
  scratched,
  created_date,
  created_by,
  modified_date,
  modified_by
FROM public.contest_entry;

GRANT SELECT ON api.contest_entry TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.contest_entry TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON api.contest_entry TO anon, authenticated;

NOTIFY pgrst, 'reload schema';
