-- contest_stage_pool: one JSON document per contest stage (e.g. HEMA/TSL pools).
-- Run: psql -U postgres -d event_system_pro -f database/migrations/136_contest_stage_pool.sql

\connect event_system_pro

CREATE TABLE IF NOT EXISTS public.contest_stage_pool (
  contest_stage_pool_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  contest_id bigint NOT NULL,
  stage varchar(64) NOT NULL,
  pools_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  more_json jsonb DEFAULT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL DEFAULT 'c-agent',
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
  PRIMARY KEY (contest_stage_pool_id),
  CONSTRAINT contest_stage_pool_uq UNIQUE (contest_id, stage),
  CONSTRAINT contest_stage_pool_fk_contest FOREIGN KEY (contest_id)
    REFERENCES public.contest (contest_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX IF NOT EXISTS contest_stage_pool_fk_contest ON public.contest_stage_pool (contest_id);

COMMENT ON TABLE public.contest_stage_pool IS
  'One pools/stage document per contest stage (e.g. Standard pools). pools_json holds fighters, bouts, and standings.';

COMMENT ON COLUMN public.contest_stage_pool.stage IS
  'Stage key mirrored from pools_json.stage (e.g. pools, primary_elim, redemption).';

COMMENT ON COLUMN public.contest_stage_pool.pools_json IS
  'Contest stage document: labels, rules, pools[], bouts, and standings.';

DROP TRIGGER IF EXISTS trg_set_modified_audit ON public.contest_stage_pool;
CREATE TRIGGER trg_set_modified_audit
  BEFORE UPDATE ON public.contest_stage_pool
  FOR EACH ROW
  EXECUTE FUNCTION public.set_row_modified_audit();

DROP TRIGGER IF EXISTS trg_audit_row_change ON public.contest_stage_pool;
CREATE TRIGGER trg_audit_row_change
  AFTER INSERT OR UPDATE OR DELETE ON public.contest_stage_pool
  FOR EACH ROW
  EXECUTE FUNCTION public.audit_row_change();

CREATE OR REPLACE VIEW api.contest_stage_pool AS
SELECT
  contest_stage_pool_id,
  contest_id,
  stage,
  pools_json,
  more_json,
  created_date,
  created_by,
  modified_date,
  modified_by
FROM public.contest_stage_pool;

GRANT SELECT ON api.contest_stage_pool TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.contest_stage_pool TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON api.contest_stage_pool TO anon, authenticated;

CREATE OR REPLACE FUNCTION api.get_contest_stage_pool(
  p_contest_id bigint,
  p_stage text
)
RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, api
AS $$
DECLARE
  v_actor_id bigint;
  v_stage text;
  v_row public.contest_stage_pool%ROWTYPE;
BEGIN
  v_actor_id := api.current_user_id();

  IF v_actor_id IS NULL THEN
    RETURN json_build_object('ok', false, 'message', 'Sign in to view contest stage pools.');
  END IF;

  IF NOT api.has_app_role('ADMIN') THEN
    RETURN json_build_object(
      'ok', false,
      'message', 'Only an admin can view contest stage pools.'
    );
  END IF;

  IF p_contest_id IS NULL THEN
    RETURN json_build_object('ok', false, 'message', 'Contest id is required.');
  END IF;

  v_stage := nullif(btrim(COALESCE(p_stage, '')), '');

  IF v_stage IS NULL THEN
    RETURN json_build_object('ok', false, 'message', 'Stage is required.');
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.contest AS c
    WHERE c.contest_id = p_contest_id
  ) THEN
    RETURN json_build_object('ok', false, 'message', 'Contest was not found.');
  END IF;

  SELECT *
  INTO v_row
  FROM public.contest_stage_pool AS csp
  WHERE csp.contest_id = p_contest_id
    AND csp.stage = v_stage;

  IF NOT FOUND THEN
    RETURN json_build_object(
      'ok', true,
      'contest_id', p_contest_id,
      'stage', v_stage,
      'found', false,
      'pools_json', '{}'::jsonb
    );
  END IF;

  RETURN json_build_object(
    'ok', true,
    'contest_id', v_row.contest_id,
    'stage', v_row.stage,
    'found', true,
    'contest_stage_pool_id', v_row.contest_stage_pool_id,
    'pools_json', v_row.pools_json,
    'more_json', v_row.more_json
  );
END;
$$;

CREATE OR REPLACE FUNCTION api.save_contest_stage_pool(
  p_contest_id bigint,
  p_stage text,
  p_pools_json json DEFAULT '{}'::json,
  p_more_json json DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, api
AS $$
DECLARE
  v_actor_id bigint;
  v_actor text;
  v_stage text;
  v_pools jsonb;
  v_more jsonb;
  v_id bigint;
BEGIN
  v_actor_id := api.current_user_id();

  IF v_actor_id IS NULL THEN
    RETURN json_build_object('ok', false, 'message', 'Sign in to save contest stage pools.');
  END IF;

  IF NOT api.has_app_role('ADMIN') THEN
    RETURN json_build_object(
      'ok', false,
      'message', 'Only an admin can save contest stage pools.'
    );
  END IF;

  IF p_contest_id IS NULL THEN
    RETURN json_build_object('ok', false, 'message', 'Contest id is required.');
  END IF;

  v_stage := nullif(btrim(COALESCE(p_stage, '')), '');

  IF v_stage IS NULL THEN
    RETURN json_build_object('ok', false, 'message', 'Stage is required.');
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.contest AS c
    WHERE c.contest_id = p_contest_id
  ) THEN
    RETURN json_build_object('ok', false, 'message', 'Contest was not found.');
  END IF;

  IF p_pools_json IS NULL OR json_typeof(p_pools_json) <> 'object' THEN
    RETURN json_build_object('ok', false, 'message', 'pools_json must be a JSON object.');
  END IF;

  v_pools := coalesce(p_pools_json::jsonb, '{}'::jsonb);

  IF p_more_json IS NULL THEN
    v_more := NULL;
  ELSIF json_typeof(p_more_json) <> 'object' THEN
    RETURN json_build_object('ok', false, 'message', 'more_json must be a JSON object or null.');
  ELSE
    v_more := p_more_json::jsonb;
  END IF;

  -- Keep the indexed stage column aligned with the document when present.
  IF v_pools ? 'stage' AND nullif(btrim(v_pools->>'stage'), '') IS NOT NULL THEN
    v_stage := btrim(v_pools->>'stage');
  ELSE
    v_pools := jsonb_set(v_pools, '{stage}', to_jsonb(v_stage), true);
  END IF;

  IF NOT (v_pools ? 'contest_id') OR (v_pools->>'contest_id') IS NULL THEN
    v_pools := jsonb_set(v_pools, '{contest_id}', to_jsonb(p_contest_id), true);
  END IF;

  v_actor := coalesce(nullif(btrim(api.current_username()), ''), 'admin');
  PERFORM api.set_audit_actor(v_actor);

  INSERT INTO public.contest_stage_pool (
    contest_id,
    stage,
    pools_json,
    more_json,
    created_by
  )
  VALUES (
    p_contest_id,
    v_stage,
    v_pools,
    v_more,
    left(v_actor, 128)
  )
  ON CONFLICT (contest_id, stage) DO UPDATE
  SET
    pools_json = EXCLUDED.pools_json,
    more_json = EXCLUDED.more_json,
    modified_by = left(v_actor, 128),
    modified_date = CURRENT_TIMESTAMP
  RETURNING contest_stage_pool_id INTO v_id;

  RETURN json_build_object(
    'ok', true,
    'message', 'Contest stage pool saved.',
    'contest_stage_pool_id', v_id,
    'contest_id', p_contest_id,
    'stage', v_stage,
    'pools_json', v_pools,
    'more_json', v_more
  );
END;
$$;

REVOKE ALL ON FUNCTION api.get_contest_stage_pool(bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION api.get_contest_stage_pool(bigint, text) TO authenticated;

REVOKE ALL ON FUNCTION api.save_contest_stage_pool(bigint, text, json, json) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION api.save_contest_stage_pool(bigint, text, json, json) TO authenticated;

NOTIFY pgrst, 'reload schema';
