-- contest_stage_bracket: one JSON document per contest elimination stage.
-- Also adds contest.more_json for division / display metadata.
-- Run: psql -U postgres -d event_system_pro -f database/migrations/137_contest_stage_bracket.sql

\connect event_system_pro

ALTER TABLE public.contest
  ADD COLUMN IF NOT EXISTS more_json jsonb DEFAULT NULL;

COMMENT ON COLUMN public.contest.more_json IS
  'Optional contest metadata (e.g. division_key, division_label, demo flag, display name).';

DROP VIEW IF EXISTS api.contest;
CREATE VIEW api.contest AS
SELECT
  contest_id,
  event_id,
  event_type_code,
  competitors_json,
  results_json,
  more_json,
  age_division_id,
  current_heat_id,
  current_heat_index,
  media_links_json,
  is_active,
  is_cancelled,
  staff_json,
  location_json,
  male_or_female,
  number_of_heats,
  original_start_time,
  original_end_time,
  pushed_back_start_time,
  pushed_back_end_time,
  primary_contact_id,
  created_date,
  created_by,
  modified_date,
  modified_by
FROM public.contest
WHERE is_active <> 0
  AND COALESCE(is_cancelled, 0) = 0;

GRANT SELECT ON api.contest TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.contest TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON api.contest TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.contest_stage_bracket (
  contest_stage_bracket_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  contest_id bigint NOT NULL,
  stage varchar(64) NOT NULL,
  bracket_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  more_json jsonb DEFAULT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(128) NOT NULL DEFAULT 'c-agent',
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  modified_by varchar(128) NULL DEFAULT NULL,
  PRIMARY KEY (contest_stage_bracket_id),
  CONSTRAINT contest_stage_bracket_uq UNIQUE (contest_id, stage),
  CONSTRAINT contest_stage_bracket_fk_contest FOREIGN KEY (contest_id)
    REFERENCES public.contest (contest_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX IF NOT EXISTS contest_stage_bracket_fk_contest ON public.contest_stage_bracket (contest_id);

COMMENT ON TABLE public.contest_stage_bracket IS
  'One elimination-bracket document per contest stage (e.g. primary_elim). bracket_json holds rounds and matches.';

COMMENT ON COLUMN public.contest_stage_bracket.stage IS
  'Stage key mirrored from bracket_json.stage (e.g. primary_elim, redemption).';

COMMENT ON COLUMN public.contest_stage_bracket.bracket_json IS
  'Single-elimination (or similar) bracket document for this contest stage.';

DROP TRIGGER IF EXISTS trg_set_modified_audit ON public.contest_stage_bracket;
CREATE TRIGGER trg_set_modified_audit
  BEFORE UPDATE ON public.contest_stage_bracket
  FOR EACH ROW
  EXECUTE FUNCTION public.set_row_modified_audit();

DROP TRIGGER IF EXISTS trg_audit_row_change ON public.contest_stage_bracket;
CREATE TRIGGER trg_audit_row_change
  AFTER INSERT OR UPDATE OR DELETE ON public.contest_stage_bracket
  FOR EACH ROW
  EXECUTE FUNCTION public.audit_row_change();

CREATE OR REPLACE VIEW api.contest_stage_bracket AS
SELECT
  contest_stage_bracket_id,
  contest_id,
  stage,
  bracket_json,
  more_json,
  created_date,
  created_by,
  modified_date,
  modified_by
FROM public.contest_stage_bracket;

GRANT SELECT ON api.contest_stage_bracket TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.contest_stage_bracket TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON api.contest_stage_bracket TO anon, authenticated;

CREATE OR REPLACE FUNCTION api.get_contest_stage_bracket(
  p_contest_id bigint,
  p_stage text
)
RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, api
AS $$
DECLARE
  v_actor_id bigint;
  v_stage text;
  v_row public.contest_stage_bracket%ROWTYPE;
BEGIN
  v_actor_id := api.current_user_id();

  IF v_actor_id IS NULL THEN
    RETURN json_build_object('ok', false, 'message', 'Sign in to view contest stage brackets.');
  END IF;

  IF NOT api.has_app_role('ADMIN') THEN
    RETURN json_build_object(
      'ok', false,
      'message', 'Only an admin can view contest stage brackets.'
    );
  END IF;

  IF p_contest_id IS NULL THEN
    RETURN json_build_object('ok', false, 'message', 'Contest id is required.');
  END IF;

  v_stage := nullif(btrim(COALESCE(p_stage, '')), '');

  IF v_stage IS NULL THEN
    RETURN json_build_object('ok', false, 'message', 'Stage is required.');
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.contest AS c
    WHERE c.contest_id = p_contest_id
  ) THEN
    RETURN json_build_object('ok', false, 'message', 'Contest was not found.');
  END IF;

  SELECT *
  INTO v_row
  FROM public.contest_stage_bracket AS csb
  WHERE csb.contest_id = p_contest_id
    AND csb.stage = v_stage;

  IF NOT FOUND THEN
    RETURN json_build_object(
      'ok', true,
      'contest_id', p_contest_id,
      'stage', v_stage,
      'found', false,
      'bracket_json', '{}'::jsonb
    );
  END IF;

  RETURN json_build_object(
    'ok', true,
    'contest_id', v_row.contest_id,
    'stage', v_row.stage,
    'found', true,
    'contest_stage_bracket_id', v_row.contest_stage_bracket_id,
    'bracket_json', v_row.bracket_json,
    'more_json', v_row.more_json
  );
END;
$$;

CREATE OR REPLACE FUNCTION api.save_contest_stage_bracket(
  p_contest_id bigint,
  p_stage text,
  p_bracket_json json DEFAULT '{}'::json,
  p_more_json json DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, api
AS $$
DECLARE
  v_actor_id bigint;
  v_actor text;
  v_stage text;
  v_bracket jsonb;
  v_more jsonb;
  v_id bigint;
BEGIN
  v_actor_id := api.current_user_id();

  IF v_actor_id IS NULL THEN
    RETURN json_build_object('ok', false, 'message', 'Sign in to save contest stage brackets.');
  END IF;

  IF NOT api.has_app_role('ADMIN') THEN
    RETURN json_build_object(
      'ok', false,
      'message', 'Only an admin can save contest stage brackets.'
    );
  END IF;

  IF p_contest_id IS NULL THEN
    RETURN json_build_object('ok', false, 'message', 'Contest id is required.');
  END IF;

  v_stage := nullif(btrim(COALESCE(p_stage, '')), '');

  IF v_stage IS NULL THEN
    RETURN json_build_object('ok', false, 'message', 'Stage is required.');
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.contest AS c
    WHERE c.contest_id = p_contest_id
  ) THEN
    RETURN json_build_object('ok', false, 'message', 'Contest was not found.');
  END IF;

  IF p_bracket_json IS NULL OR json_typeof(p_bracket_json) <> 'object' THEN
    RETURN json_build_object('ok', false, 'message', 'bracket_json must be a JSON object.');
  END IF;

  v_bracket := coalesce(p_bracket_json::jsonb, '{}'::jsonb);

  IF p_more_json IS NULL THEN
    v_more := NULL;
  ELSIF json_typeof(p_more_json) <> 'object' THEN
    RETURN json_build_object('ok', false, 'message', 'more_json must be a JSON object or null.');
  ELSE
    v_more := p_more_json::jsonb;
  END IF;

  IF v_bracket ? 'stage' AND nullif(btrim(v_bracket->>'stage'), '') IS NOT NULL THEN
    v_stage := btrim(v_bracket->>'stage');
  ELSE
    v_bracket := jsonb_set(v_bracket, '{stage}', to_jsonb(v_stage), true);
  END IF;

  IF NOT (v_bracket ? 'contest_id') OR (v_bracket->>'contest_id') IS NULL THEN
    v_bracket := jsonb_set(v_bracket, '{contest_id}', to_jsonb(p_contest_id), true);
  END IF;

  v_actor := coalesce(nullif(btrim(api.current_username()), ''), 'admin');
  PERFORM api.set_audit_actor(v_actor);

  INSERT INTO public.contest_stage_bracket (
    contest_id,
    stage,
    bracket_json,
    more_json,
    created_by
  )
  VALUES (
    p_contest_id,
    v_stage,
    v_bracket,
    v_more,
    left(v_actor, 128)
  )
  ON CONFLICT (contest_id, stage) DO UPDATE
  SET
    bracket_json = EXCLUDED.bracket_json,
    more_json = EXCLUDED.more_json,
    modified_by = left(v_actor, 128),
    modified_date = CURRENT_TIMESTAMP
  RETURNING contest_stage_bracket_id INTO v_id;

  RETURN json_build_object(
    'ok', true,
    'message', 'Contest stage bracket saved.',
    'contest_stage_bracket_id', v_id,
    'contest_id', p_contest_id,
    'stage', v_stage,
    'bracket_json', v_bracket,
    'more_json', v_more
  );
END;
$$;

REVOKE ALL ON FUNCTION api.get_contest_stage_bracket(bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION api.get_contest_stage_bracket(bigint, text) TO authenticated;

REVOKE ALL ON FUNCTION api.save_contest_stage_bracket(bigint, text, json, json) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION api.save_contest_stage_bracket(bigint, text, json, json) TO authenticated;

NOTIFY pgrst, 'reload schema';
