CREATE TABLE IF NOT EXISTS user_preference (
  user_preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id bigint DEFAULT NULL,
  label varchar(64) DEFAULT NULL,
  value varchar(256) DEFAULT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_by varchar(128) DEFAULT NULL,
  created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_by varchar(128) DEFAULT NULL,
  modified_date TIMESTAMPTZ NULL DEFAULT NULL,
  PRIMARY KEY (user_preference_id),
  CONSTRAINT user_preference_ibfk_1 FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX IF NOT EXISTS fk_up_user_id ON user_preference (user_id);
