"""Image Comics hero and villain seed data."""

# username, first, last, publisher, sex, color1, color2
IMAGE_HEROES: list[tuple[str, str, str, str, str | None, str | None, str | None]] = [
    ("invincible", "Mark", "Grayson", "Image", "male", "yellow", "blue"),
    ("atom eve", "Samantha", "Eve", "Image", "female", "pink", "white"),
    ("omniman", "Nolan", "Grayson", "Image", "male", "red", "white"),
    ("allenalien", "Allen", "Alien", "Image", "male", "orange", "blue"),
    ("robot", "Rudolph", "Connors", "Image", "male", "red", "gray"),
    ("rexsplode", "Rex", "Sloan", "Image", "male", "orange", "blue"),
    ("duplikate", "Kate", "Cha", "Image", "female", "purple", "black"),
    ("monstergirl", "Amanda", "Young", "Image", "female", "green", "black"),
    ("immortal", "Abraham", "Lincoln", "Image", "male", "green", "yellow"),
    ("bulletproof", "Zandale", "Randolph", "Image", "male", "yellow", "blue"),
    ("blacksamson", "Marcus", "Grimshaw", "Image", "male", "black", "yellow"),
    ("warwoman", "Holly", "Winters", "Image", "female", "red", "gold"),
    ("shrinkray", "Rae", "Murphy", "Image", "female", "blue", "white"),
    ("greenghost", "Alana", "Michaels", "Image", "female", "green", "white"),
    ("darkwing", "Damien", "Darkblood", "Image", "male", "black", "gray"),
    ("besttiger", "Theo", "Kane", "Image", "male", "orange", "black"),
    ("brit", "Britt", "Reid", "Image", "male", "blue", "gray"),
    ("techjacket", "Zack", "Thompson", "Image", "male", "blue", "silver"),
    ("spawn", "Al", "Simmons", "Image", "male", "black", "red"),
    ("witchblade", "Sara", "Pezzini", "Image", "female", "gold", "black"),
    ("darkness", "Jackie", "Estacado", "Image", "male", "black", "blue"),
    ("savage dragon", "Malcolm", "Dragon", "Image", "male", "green", "blue"),
    ("shadowhawk", "Paul", "Johnstone", "Image", "male", "black", "silver"),
    ("youngblood shaft", "Richard", "Olmstead", "Image", "male", "blue", "white"),
    ("youngblood chapel", "Bruce", "Stinson", "Image", "male", "black", "white"),
    ("youngblood badrock", "Thomas", "Jr", "Image", "male", "brown", "gray"),
    ("youngblood vogue", "Nikki", "Doyle", "Image", "female", "purple", "black"),
    ("youngblood diehard", "Lyle", "Kane", "Image", "male", "red", "black"),
    ("youngblood combat", "Jamie", "Sanchez", "Image", "male", "green", "black"),
    ("youngblood riptide", "Rita", "Delaney", "Image", "female", "blue", "white"),
    ("supreme", "Ethan", "Crane", "Image", "male", "blue", "red"),
    ("glory", "Gloriana", "Demeter", "Image", "female", "gold", "red"),
    ("bloodstrike fourplay", "Avril", "Graham", "Image", "female", "red", "black"),
    ("bloodstrike cabot", "Cabbot", "Stone", "Image", "male", "gray", "black"),
    ("prophet", "John", "Prophet", "Image", "male", "brown", "green"),
    ("brigade battlestone", "Stony", "Briggs", "Image", "male", "blue", "gray"),
    ("brigade sea hawk", "Kayo", "Tanaka", "Image", "female", "blue", "gold"),
    ("firebreather", "Duncan", "Rosenblatt", "Image", "male", "red", "orange"),
    ("noblecauses docnoble", "Doc", "Noble", "Image", "male", "blue", "white"),
    ("noblecauses race", "Race", "Noble", "Image", "male", "red", "white"),
    ("noblecauses zephyr", "Zephyr", "Noble", "Image", "female", "white", "blue"),
    ("noblecauses frost", "Frost", "Noble", "Image", "male", "cyan", "white"),
    ("noblecauses gaia", "Gaia", "Noble", "Image", "female", "green", "gold"),
    ("noblecauses rusty", "Rusty", "Noble", "Image", "male", "brown", "orange"),
    ("radiantblack", "Nathan", "Burnett", "Image", "male", "black", "pink"),
    ("radiantred", "Satomi", "Sone", "Image", "female", "red", "black"),
    ("radiantpink", "Eva", "Reyes", "Image", "female", "pink", "white"),
    ("radiantyellow", "Wendell", "Walters", "Image", "male", "yellow", "black"),
    ("roguesun", "Dylan", "Siegel", "Image", "male", "orange", "red"),
    ("inferno girl red", "Cami", "Ridge", "Image", "female", "red", "white"),
    ("deadlucky", "Bibi", "Lopez", "Image", "female", "green", "black"),
    ("supermassive", "Maya", "King", "Image", "female", "purple", "blue"),
    ("geiger", "Tariq", "Geiger", "Image", "male", "green", "yellow"),
    ("junkyardjoe", "Joseph", "Mason", "Image", "male", "gray", "green"),
    ("redcoat", "Simon", "Pure", "Image", "male", "red", "white"),
    ("voidrivalk", "Tara", "Rivalk", "Image", "female", "black", "violet"),
    ("wolfman", "Gary", "Hampton", "Image", "male", "brown", "black"),
    ("guardinglobe", "Britney", "Cho", "Image", "female", "blue", "gold"),
    ("sara", "Sara", "Pezzini", "Image", "female", "gold", "black"),
    ("velocity", "Carin", "Taylor", "Image", "female", "blue", "white"),
    ("cyblade", "Stryk", "Velocity", "Image", "female", "red", "silver"),
    ("ripclaw", "William", "Talbot", "Image", "male", "black", "red"),
    ("grifter", "Cole", "Cash", "Image", "male", "red", "black"),
    ("zealot", "Lady", "Zannah", "Image", "female", "white", "red"),
    ("voodoo", "Priscilla", "Kitaen", "Image", "female", "purple", "black"),
    ("maul", "Jeremy", "Stone", "Image", "male", "orange", "gray"),
    ("spartan", "Yohn", "Kall", "Image", "male", "blue", "silver"),
    ("warblade", "Michael", "Cray", "Image", "male", "black", "silver"),
    ("fairchild", "Caitlin", "Fairchild", "Image", "female", "red", "blue"),
    ("burnout", "Bobby", "Lane", "Image", "male", "orange", "red"),
    ("rainmaker", "Sarah", "Rainmaker", "Image", "female", "blue", "green"),
    ("freefall", "Roxy", "Spaulding", "Image", "female", "purple", "pink"),
    ("boon", "Jeremy", "Boon", "Image", "male", "green", "silver"),
    ("newmen", "Nicholas", "Neman", "Image", "male", "blue", "gray"),
    ("kickass", "Dave", "Lizewski", "Image", "male", "green", "yellow"),
    ("hitgirl", "Mindy", "Macready", "Image", "female", "purple", "black"),
    ("nemesis", "Matt", "Anderson", "Image", "male", "white", "black"),
    ("kingsman", "Gary", "Unwin", "Image", "male", "blue", "black"),
    ("chrononaut", "Corbin", "Quinn", "Image", "male", "blue", "gold"),
    ("reborn", "Bonnie", "Black", "Image", "female", "white", "gold"),
    ("skybound rogue", "Tyler", "Wells", "Image", "male", "teal", "black"),
]
