import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MYSQL_DUMP = ROOT / "database" / "event-system-pro" / "tsl_db_dump_navicat_2021_04_04.sql"
PG_OUTPUT = ROOT / "database" / "event-system-pro" / "evp_schema_postgresql.sql"

TABLE_RENAMES = {
    "fight_event_group": "event_group",
    "fight_event": "event",
}

TABLE_ORDER = [
    "competitor_type_lu", "country_lu", "us_state_lu", "secret_question_lu",
    "skill_level_lu", "event_type_lu", "fight_event_group", "fight_event",
    "charter", "user", "contact", "image", "system_config", "contest",
    "competitor", "contest_heat", "event_staff_pool", "user_preference",
]

def pg_table_name(mysql_table: str) -> str:
    return TABLE_RENAMES.get(mysql_table, mysql_table)

def strip_mysql_identifiers(text):
    return text.replace("`", "")

def convert_column_type(col_def):
    col_def = re.sub(r"CHARACTER SET \w+ COLLATE \w+", "", col_def, flags=re.I)
    col_def = re.sub(r"\s+", " ", col_def).strip()
    replacements = [
        (r"bigint\s+NOT NULL\s+AUTO_INCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY"),
        (r"int\s+unsigned\s+NOT NULL\s+AUTO_INCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY"),
        (r"smallint\s+NOT NULL\s+AUTO_INCREMENT", "SMALLINT GENERATED BY DEFAULT AS IDENTITY"),
        (r"int\s+NOT NULL\s+AUTO_INCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY"),
        (r"\btinyint\(1\)(?=\s)", "BOOLEAN"),
        (r"\btinyint\b", "SMALLINT"),
        (r"\bmediumint\b", "INTEGER"),
        (r"\bint unsigned\b", "INTEGER"),
        (r"\bjson\b", "JSONB"),
        (r"\bblob\b", "BYTEA"),
        (r"\bdatetime\b", "TIMESTAMP"),
        (r"\btimestamp\b", "TIMESTAMPTZ"),
        (r"DEFAULT '1970-01-01 02:00:01'", "DEFAULT TIMESTAMPTZ '1970-01-01 02:00:01+00'"),
        (r"DEFAULT '0000-00-00 00:00:00'", "DEFAULT NULL"),
        (r"TIMESTAMPTZ NOT NULL DEFAULT TIMESTAMPTZ", "TIMESTAMPTZ NOT NULL DEFAULT"),
        (r"TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00'", "TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP"),
        (r"TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP", "TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP"),
        (r"BOOLEAN DEFAULT '1'", "BOOLEAN DEFAULT TRUE"),
        (r"BOOLEAN DEFAULT '0'", "BOOLEAN DEFAULT FALSE"),
        (r"BOOLEAN NOT NULL DEFAULT '1'", "BOOLEAN NOT NULL DEFAULT TRUE"),
        (r"BOOLEAN NOT NULL DEFAULT '0'", "BOOLEAN NOT NULL DEFAULT FALSE"),
        (r"TIMESTAMPTZ NOT NULL DEFAULT NULL", "TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP"),
        (r"TIMESTAMP NOT NULL DEFAULT NULL", "TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP"),
    ]
    for pattern, repl in replacements:
        col_def = re.sub(pattern, repl, col_def, flags=re.I)
    col_def = re.sub(r"\bint\b", "INTEGER", col_def, flags=re.I)
    return col_def.strip()

def quote_pg_identifier(name):
    return f'"{name}"' if name.lower() in {"user", "event"} else name

def split_sql_values(values: str) -> list[str]:
    parts, current, in_quote, escape = [], [], False, False
    for ch in values:
        if escape:
            current.append(ch)
            escape = False
            continue
        if in_quote:
            if ch == "\\":
                escape = True
                current.append(ch)
            elif ch == "'":
                in_quote = False
                current.append(ch)
            else:
                current.append(ch)
            continue
        if ch == "'":
            in_quote = True
            current.append(ch)
            continue
        if ch == ",":
            parts.append("".join(current).strip())
            current = []
            continue
        current.append(ch)
    parts.append("".join(current).strip())
    return parts

def parse_table_columns(body: str) -> list[tuple[str, str]]:
    columns = []
    for line in body.splitlines():
        line = strip_mysql_identifiers(line.strip()).rstrip(",")
        if not line or line.upper().startswith(("PRIMARY KEY", "UNIQUE KEY", "KEY ", "CONSTRAINT")):
            continue
        parts = line.split(None, 1)
        if len(parts) == 2:
            columns.append((parts[0], convert_column_type(parts[1])))
    return columns

def parse_create_tables(content):
    tables, table_columns = {}, {}
    pattern = re.compile(r"DROP TABLE IF EXISTS `(\w+)`;\s*CREATE TABLE `\1` \((.*?)\) ENGINE=\w+[^;]*;", re.S | re.I)
    for match in pattern.finditer(content):
        table_name = match.group(1)
        body = match.group(2)
        table_columns[table_name] = parse_table_columns(body)
        lines = [ln.strip() for ln in body.splitlines() if ln.strip()]
        converted_lines, post_indexes, inline_constraints = [], [], []
        for line in lines:
            line = strip_mysql_identifiers(line).rstrip(",")
            upper = line.upper()
            if upper.startswith(("PRIMARY KEY", "UNIQUE KEY", "KEY ", "CONSTRAINT")):
                line = re.sub(r"\s+USING BTREE", "", line, flags=re.I)
                line = re.sub(r"UNIQUE KEY `?\w+`?", "UNIQUE", line, flags=re.I)
                if upper.startswith("KEY "):
                    idx = re.sub(r"KEY `?(\w+)`?", r"\1", line)
                    m = re.match(r"(\w+) \((.+)\)", idx, flags=re.I)
                    if m:
                        post_indexes.append(
                            f"CREATE INDEX IF NOT EXISTS {m.group(1)} ON {quote_pg_identifier(pg_table_name(table_name))} ({m.group(2)});"
                        )
                    continue
                line = re.sub(r"REFERENCES `user`", 'REFERENCES "user"', line, flags=re.I)
                line = re.sub(r"REFERENCES user \(", 'REFERENCES "user" (', line, flags=re.I)
                line = re.sub(r"REFERENCES `fight_event`", 'REFERENCES "event"', line, flags=re.I)
                line = re.sub(r"REFERENCES fight_event \(", 'REFERENCES "event" (', line, flags=re.I)
                inline_constraints.append(line)
                continue
            parts = line.split(None, 1)
            if len(parts) == 2:
                col_name, rest = parts
                converted_lines.append(f"  {quote_pg_identifier(col_name)} {convert_column_type(rest)}")
            else:
                converted_lines.append(f"  {line}")
        ddl = (
            "CREATE TABLE IF NOT EXISTS "
            + quote_pg_identifier(pg_table_name(table_name))
            + " (\n"
            + ",\n".join(converted_lines + inline_constraints)
            + "\n);"
        )
        ddl = re.sub(r",\s*UNIQUE \(contest_id\)", "", ddl, flags=re.I)
        if post_indexes:
            ddl += "\n" + "\n".join(post_indexes)
        tables[table_name] = ddl
    return tables, table_columns

def convert_insert_values(table: str, values: str, table_columns: dict) -> str:
    cols = table_columns.get(table, [])
    parts = split_sql_values(values)
    if len(parts) != len(cols):
        return values.replace("\\'", "''")
    converted = []
    for (col_name, col_type), val in zip(cols, parts):
        if col_type.upper().startswith("BOOLEAN"):
            v = val.strip().lower()
            if v in ("'1'", "1"):
                converted.append("TRUE")
            elif v in ("'0'", "0"):
                converted.append("FALSE")
            else:
                converted.append(val)
        else:
            converted.append(val)
    out = ", ".join(converted)
    return out.replace("\\'", "''")

def parse_inserts(content, table_columns):
    inserts = {}
    for match in re.finditer(r"INSERT INTO `(\w+)` VALUES \((.*)\);", content, flags=re.I):
        table, values = match.group(1), match.group(2)
        values = convert_insert_values(table, values, table_columns)
        values = re.sub(r"\bnull\b", "NULL", values, flags=re.I)
        inserts.setdefault(table, []).append(
            f"INSERT INTO {quote_pg_identifier(pg_table_name(table))} VALUES ({values});"
        )
    return inserts

content = MYSQL_DUMP.read_text(encoding="utf-8")
tables, table_columns = parse_create_tables(content)
inserts = parse_inserts(content, table_columns)

header = """-- Event System Pro PostgreSQL schema and seed data
-- Baseline for database: event_system_pro
-- Regenerated from database/event-system-pro/tsl_db_dump_navicat_2021_04_04.sql (legacy MySQL dump)

-- Step 1: create database (as superuser)
--   psql -U postgres -c \"CREATE DATABASE event_system_pro WITH ENCODING 'UTF8' TEMPLATE template0;\"
--
-- Step 2: apply schema and seed data
--   psql -U postgres -d event_system_pro -f database/event-system-pro/evp_schema_postgresql.sql

\\connect event_system_pro

SET client_encoding = 'UTF8';

DROP TABLE IF EXISTS user_preference CASCADE;
DROP TABLE IF EXISTS event_staff_pool CASCADE;
DROP TABLE IF EXISTS contest_heat CASCADE;
DROP TABLE IF EXISTS competitor CASCADE;
DROP TABLE IF EXISTS contest CASCADE;
DROP TABLE IF EXISTS contact CASCADE;
DROP TABLE IF EXISTS image CASCADE;
DROP TABLE IF EXISTS system_config CASCADE;
DROP TABLE IF EXISTS charter CASCADE;
DROP TABLE IF EXISTS \"user\" CASCADE;
DROP TABLE IF EXISTS \"event\" CASCADE;
DROP TABLE IF EXISTS event_group CASCADE;
DROP TABLE IF EXISTS event_type_lu CASCADE;
DROP TABLE IF EXISTS skill_level_lu CASCADE;
DROP TABLE IF EXISTS secret_question_lu CASCADE;
DROP TABLE IF EXISTS us_state_lu CASCADE;
DROP TABLE IF EXISTS country_lu CASCADE;
DROP TABLE IF EXISTS competitor_type_lu CASCADE;

"""

parts = [header]
for table in TABLE_ORDER:
    if table in tables:
        parts.append(f"-- Table: {pg_table_name(table)}\n" + tables[table] + "\n")

parts.append("-- Seed data\n")
for table in TABLE_ORDER:
    if table in inserts:
        parts.extend(inserts[table])

parts.append("\n-- Align identity sequences with seeded primary keys\n")
for table, col in [("country_lu","country_id"),("us_state_lu","id"),("secret_question_lu","secret_question_id"),("fight_event","event_id")]:
    pg_table = pg_table_name(table)
    parts.append(
        f"SELECT setval(pg_get_serial_sequence('{pg_table}', '{col}'), COALESCE((SELECT MAX({col}) FROM {quote_pg_identifier(pg_table)}), 1));"
    )

PG_OUTPUT.write_text("\n".join(parts), encoding="utf-8")
print(f"Wrote {PG_OUTPUT} ({PG_OUTPUT.stat().st_size} bytes)")