"""DC replacement heroes for users that would otherwise have last name 'Character'.

Squadron Supreme, Crime Syndicate, Fatal Five, and Lantern corps (all colors).
# username, first, last, publisher, sex, color1, color2
"""

REPLACEMENT_DC_HEROES: list[tuple[str, str, str, str, str | None, str | None, str | None]] = [
    ("hyperion", "Mark", "Milton", "Marvel", "male", "blue", "black"),
    ("nighthawk", "Kyle", "Richmond", "Marvel", "male", "black", "yellow"),
    ("powerprincess", "Zarda", "Shelton", "Marvel", "female", "white", "gold"),
    ("whizzer", "Stanley", "Stewart", "Marvel", "male", "red", "yellow"),
    ("doctorspectrum", "Joseph", "Perlman", "Marvel", "male", "red", "yellow"),
    ("skrullianskymaster", "Martin", "Burns", "Marvel", "male", "green", "gold"),
    ("amphibian", "Kingsley", "Rice", "Marvel", "male", "green", "black"),
    ("arcanna", "Arcanna", "Jones", "Marvel", "female", "green", "brown"),
    ("goldenarcher", "Wyatt", "McDonald", "Marvel", "male", "gold", "green"),
    ("lamprey", "Donald", "Gill", "Marvel", "male", "blue", "black"),
    ("nuke", "Albert", "Gaines", "Marvel", "male", "green", "yellow"),
    ("shape", "Raleigh", "Lund", "Marvel", "male", "purple", "white"),
    ("tomthumb", "Thomas", "Thompson", "Marvel", "male", "blue", "red"),
    ("blueeagle", "James", "Dore", "Marvel", "male", "blue", "white"),
    ("foxfire", "Olisa", "Lawson", "Marvel", "female", "orange", "red"),
    ("mink", "Jerome", "McElroy", "Marvel", "male", "brown", "black"),
    ("pinball", "Robbie", "Stewart", "Marvel", "male", "red", "blue"),
    ("emeryworld", "Emery", "World", "Marvel", "male", "yellow", "green"),
    ("farmerbones", "Farmer", "Bones", "Marvel", "male", "white", "brown"),
    ("moonglow", "Lorna", "Schultz", "Marvel", "female", "silver", "blue"),
    ("squadronprincess", "Aleta", "Vanguard", "Marvel", "female", "white", "gold"),
    ("squadronnighthawk", "Neal", "Richmond", "Marvel", "male", "black", "red"),
    ("squadronhyperion", "Marcus", "Milton", "Marvel", "male", "blue", "red"),
  # Crime Syndicate
    ("ultraman", "Clark", "Kent", "DC", "male", "blue", "red"),
    ("owlman", "Thomas", "Wayne", "DC", "male", "black", "gray"),
    ("superwoman", "Lois", "Lane", "DC", "female", "blue", "red"),
    ("johnnyquick", "Jonathan", "Allen", "DC", "male", "red", "yellow"),
    ("powerring", "Joseph", "Harro", "DC", "male", "green", "black"),
    ("deathstorm", "Martin", "Stein", "DC", "male", "white", "black"),
    ("seaking", "Arthur", "Curry", "DC", "male", "green", "gold"),
    ("atomica", "Rhonda", "Pineda", "DC", "female", "red", "blue"),
    ("crimesyndicategrid", "Grid", "Syndicate", "DC", "male", "gray", "red"),
    ("murdermachine", "Bruce", "Wayne", "DC", "male", "red", "black"),
    ("dawnbreaker", "Bruce", "Wayne", "DC", "male", "green", "black"),
    ("themerciless", "Diana", "Prince", "DC", "female", "red", "gold"),
    ("psycho pirate", "Roger", "Hayden", "DC", "male", "gold", "purple"),
    ("mazahs", "Alexander", "Luthor", "DC", "male", "black", "green"),
    ("outsider", "Alfred", "Pennyworth", "DC", "male", "black", "white"),
    ("crimemartian", "J'onn", "J'onzz", "DC", "male", "green", "red"),
    ("terry sloan", "Terry", "Sloan", "DC", "male", "blue", "white"),
    ("johnnyquickii", "Lydia", "Fell", "DC", "female", "red", "yellow"),
    ("owlwoman", "Leland", "McCauley", "DC", "male", "brown", "black"),
    ("ultrawoman", "Clara", "Kent", "DC", "female", "blue", "red"),
    ("ringthief", "Eugene", "Jordan", "DC", "male", "yellow", "black"),
  # Fatal Five
    ("validus", "Validus", "Bismoll", "DC", "male", "gray", "red"),
    ("emeraldempress", "Sarya", "Vandu", "DC", "female", "green", "gold"),
    ("mano", "Mano", "Yald", "DC", "male", "purple", "black"),
    ("tharok", "Tharok", "Nolan", "DC", "male", "green", "gray"),
    ("persuader", "Cole", "Parker", "DC", "male", "silver", "black"),
    ("caress", "Cinta", "Prounis", "DC", "female", "pink", "black"),
    ("mentalla", "Mia", "Dubois", "DC", "female", "purple", "white"),
    ("flare", "Ki", "Assam", "DC", "female", "orange", "yellow"),
    ("acid lizard", "Acid", "Lizard", "DC", "male", "green", "yellow"),
    ("boltlegion", "Bolt", "Legion", "DC", "male", "yellow", "blue"),
    ("emeraldempressii", "Fay", "Ardra", "DC", "female", "green", "silver"),
    ("persuaderii", "Nyeun", "Chun", "DC", "male", "gray", "black"),
    ("validusii", "Ron-Karr", "Validus", "DC", "male", "blue", "red"),
    ("tharokii", "Leland", "Tharok", "DC", "male", "green", "black"),
    ("manoii", "Mano", "Thorn", "DC", "male", "black", "purple"),
  # Green Lantern Corps
    ("haljordan", "Hal", "Jordan", "DC", "male", "brown", "black"),
    ("johnstewart", "John", "Stewart", "DC", "male", "brown", "black"),
    ("kylerayner", "Kyle", "Rayner", "DC", "male", "green", "black"),
    ("guygardner", "Guy", "Gardner", "DC", "male", "blue", "red"),
    ("kilowog", "Kilowog", "Bolovax", "DC", "male", "pink", "red"),
    ("salaak", "Salaak", "Slygg", "DC", "male", "pink", "black"),
    ("tomarre", "Tomar", "Re", "DC", "male", "blue", "brown"),
    ("arisia", "Arisia", "Rrab", "DC", "female", "green", "blue"),
    ("katmatui", "Katma", "Tui", "DC", "female", "purple", "black"),
    ("chp", "Ch'p", "Hojan", "DC", "male", "brown", "green"),
    ("boodikka", "Boodikka", "Bell", "DC", "female", "blue", "blond"),
    ("isamotkol", "Isamot", "Kol", "DC", "male", "yellow", "green"),
    ("soraniknatu", "Soranik", "Natu", "DC", "female", "pink", "black"),
    ("hannu", "Hannu", "Oa", "DC", "male", "brown", "black"),
    ("brik", "Brik", "Dryad", "DC", "female", "red", "black"),
    ("lairaomoto", "Laira", "Omoto", "DC", "female", "brown", "black"),
    ("sodamyat", "Sodam", "Yat", "DC", "male", "brown", "black"),
    ("simonbaz", "Simon", "Baz", "DC", "male", "brown", "black"),
    ("jessicacruz", "Jessica", "Cruz", "DC", "female", "brown", "black"),
    ("jomullein", "Jo", "Mullein", "DC", "female", "brown", "black"),
    ("keliquintela", "Keli", "Quintela", "DC", "female", "brown", "black"),
    ("sojournermullein", "Sojourner", "Mullein", "DC", "female", "brown", "black"),
    ("kyle rayner gl", "Kyle", "Rayner", "DC", "male", "green", "black"),
    ("medphyll", "Medphyll", "J586", "DC", "male", "green", "brown"),
    ("penelopsa", "Penelops", "Glazz", "DC", "male", "pink", "green"),
  # Sinestro Corps (yellow)
    ("sinestro", "Thaal", "Sinestro", "DC", "male", "red", "black"),
    ("arkillo", "Arkillo", "Yowat", "DC", "male", "yellow", "black"),
    ("karusil", "Karu-Sil", "Sinestro", "DC", "female", "yellow", "black"),
    ("lyssadrak", "Lyssa", "Drak", "DC", "female", "yellow", "black"),
    ("bedovian", "Bedovian", "Sinestro", "DC", "male", "yellow", "brown"),
    ("romatru", "Romat-Ru", "Sinestro", "DC", "male", "yellow", "black"),
    ("despotellis", "Despotellis", "Virus", "DC", "male", "yellow", "green"),
    ("scivor", "Scivor", "Sinestro", "DC", "male", "yellow", "gray"),
    ("slushh", "Slushh", "Sinestro", "DC", "male", "blue", "yellow"),
    ("borialosaurus", "Borialosaurus", "Krynn", "DC", "male", "yellow", "green"),
    ("ammonsur", "Amon", "Sur", "DC", "male", "yellow", "black"),
    ("mongulii", "Mongul", "Sinestro", "DC", "male", "yellow", "red"),
    ("superboyprime", "Clark", "Kent", "DC", "male", "blue", "black"),
    ("yellowlantern", "William", "Hand", "DC", "male", "yellow", "black"),
  # Red Lantern Corps
    ("atrocitus", "Atrocitus", "Ysmault", "DC", "male", "red", "black"),
    ("bleez", "Bleez", "Raven", "DC", "female", "red", "black"),
    ("rankorr", "Rankorr", "Harlan", "DC", "male", "red", "brown"),
    ("skallox", "Skallox", "Ysmault", "DC", "male", "red", "black"),
    ("ziliuszox", "Zilius", "Zox", "DC", "male", "red", "purple"),
    ("dexstarr", "Dex", "Starr", "DC", "male", "red", "orange"),
    ("judge sheko", "Judge", "Sheko", "DC", "female", "red", "black"),
    ("ratchet", "Ratchet", "Ysmault", "DC", "male", "red", "gray"),
    ("veon", "Veon", "Ysmault", "DC", "male", "red", "black"),
    ("nite lik", "Nite", "Lik", "DC", "male", "red", "purple"),
    ("horoq tso", "Horoq", "Tso", "DC", "male", "red", "black"),
    ("llira", "Llira", "Ysmault", "DC", "female", "red", "black"),
    ("redlanternmera", "Mera", "Curry", "DC", "female", "red", "black"),
    ("redguy", "Guy", "Gardner", "DC", "male", "red", "black"),
  # Orange Lantern Corps
    ("larfleeze", "Larfleeze", "Agent", "DC", "male", "orange", "black"),
    ("glomulus", "Glomulus", "Orange", "DC", "male", "orange", "yellow"),
    ("warp wrap", "Warp", "Wrap", "DC", "male", "orange", "green"),
    ("sound dancer", "Sound", "Dancer", "DC", "female", "orange", "purple"),
    ("dyltov", "Dyltov", "Orange", "DC", "male", "orange", "brown"),
    ("larfleezeii", "Avar", "Larfleeze", "DC", "male", "orange", "red"),
  # Blue Lantern Corps
    ("saintwalker", "Bro'Dee", "Walker", "DC", "male", "blue", "white"),
    ("brotherwarth", "Warth", "Walker", "DC", "male", "blue", "white"),
    ("brotherhymn", "Hymn", "Walker", "DC", "male", "blue", "white"),
    ("brotherph ti", "Ph'ti", "Walker", "DC", "male", "blue", "white"),
    ("brother ees", "Ees", "Walker", "DC", "male", "blue", "white"),
    ("adaraentity", "Adara", "Entity", "DC", "female", "blue", "white"),
    ("barryallenblue", "Barry", "Allen", "DC", "male", "blue", "red"),
    ("hopehal", "Hal", "Hope", "DC", "male", "blue", "brown"),
  # Indigo Tribe
    ("indigoone", "Ikriptis", "Indigo", "DC", "female", "indigo", "black"),
    ("munk", "Munk", "Indigo", "DC", "male", "indigo", "black"),
    ("rayo", "Rayo", "Indigo", "DC", "male", "indigo", "white"),
    ("profht", "Profht", "Indigo", "DC", "male", "indigo", "black"),
    ("kreaven", "Kreaven", "Indigo", "DC", "male", "indigo", "gray"),
    ("indigokid", "Kid", "Indigo", "DC", "male", "indigo", "black"),
  # Star Sapphire / Violet Lantern Corps
    ("carolferris", "Carol", "Ferris", "DC", "female", "violet", "blond"),
    ("fatality", "Yrra", "Cynyl", "DC", "female", "violet", "black"),
    ("miririam", "Miri", "Riam", "DC", "female", "violet", "brown"),
    ("delapharon", "Dela", "Pharon", "DC", "female", "violet", "black"),
    ("avrakehd", "Avra", "Kehd", "DC", "female", "violet", "brown"),
    ("pazupinder", "Pazu", "Pinder", "DC", "male", "violet", "black"),
    ("khea tarek", "Khea", "Tarek", "DC", "female", "violet", "gold"),
    ("missblossom", "Miss", "Blossom", "DC", "female", "violet", "pink"),
    ("starchild", "Star", "Child", "DC", "female", "violet", "white"),
    ("lyrafatalis", "Lyra", "Fatalis", "DC", "female", "violet", "black"),
  # Black Lantern Corps
    ("blackhand", "William", "Hand", "DC", "male", "black", "white"),
    ("scar", "Scar", "Guardian", "DC", "female", "black", "red"),
    ("nekron", "Nekron", "Death", "DC", "male", "black", "white"),
    ("blacklanternsuperman", "Kal", "El", "DC", "male", "black", "white"),
    ("blacklanternbatman", "Bruce", "Wayne", "DC", "male", "black", "gray"),
    ("blacklanternwonderwoman", "Diana", "Prince", "DC", "female", "black", "gold"),
    ("blacklanternflash", "Barry", "Allen", "DC", "male", "black", "yellow"),
    ("blacklanterngreenarrow", "Oliver", "Queen", "DC", "male", "black", "green"),
  # White Lantern Corps
    ("whitelanternkyle", "Kyle", "Rayner", "DC", "male", "white", "green"),
    ("whitelanternsinestro", "Thaal", "Sinestro", "DC", "male", "white", "yellow"),
    ("whitelanterndeadman", "Boston", "Brand", "DC", "male", "white", "red"),
    ("whitelanternflash", "Barry", "Allen", "DC", "male", "white", "yellow"),
    ("whitelanternaquaman", "Arthur", "Curry", "DC", "male", "white", "green"),
    ("whitelanternsuperman", "Clark", "Kent", "DC", "male", "white", "blue"),
    ("whitelanternbatman", "Bruce", "Wayne", "DC", "male", "white", "black"),
    ("whitelanternwonderwoman", "Diana", "Prince", "DC", "female", "white", "gold"),
    # Squadron Supreme / Marvel adjuncts
    ("squadronsupreme", "Mark", "Milton", "Marvel", "male", "blue", "red"),
    ("squadronnight", "Neal", "Richmond", "Marvel", "male", "black", "yellow"),
    ("squadronpower", "Zarda", "Shelton", "Marvel", "female", "white", "gold"),
    ("squadronwhiz", "Stanley", "Stewart", "Marvel", "male", "red", "yellow"),
    ("squadrondoctor", "Ken", "Horton", "Marvel", "male", "red", "yellow"),
    ("squadronamph", "Kingsley", "Rice", "Marvel", "male", "green", "black"),
    ("squadronarc", "Arcanna", "Jones", "Marvel", "female", "green", "brown"),
    ("squadronlamp", "Donald", "Gill", "Marvel", "male", "blue", "black"),
    ("squadronnuke", "Albert", "Gaines", "Marvel", "male", "green", "yellow"),
    ("squadronshape", "Raleigh", "Lund", "Marvel", "male", "purple", "white"),
    ("squadronthumb", "Thomas", "Thompson", "Marvel", "male", "blue", "red"),
    ("squadronblue", "James", "Dore", "Marvel", "male", "blue", "white"),
    ("squadronfox", "Olisa", "Lawson", "Marvel", "female", "orange", "red"),
    ("squadronmink", "Jerome", "McElroy", "Marvel", "male", "brown", "black"),
    ("squadronpin", "Robbie", "Stewart", "Marvel", "male", "red", "blue"),
    # More Crime Syndicate / Earth-3
    ("earth3batman", "Thomas", "Wayne", "DC", "male", "black", "gray"),
    ("earth3superman", "Clark", "Kent", "DC", "male", "blue", "red"),
    ("earth3wonderwoman", "Lois", "Lane", "DC", "female", "blue", "red"),
    ("earth3flash", "Jonathan", "Allen", "DC", "male", "red", "yellow"),
    ("earth3greenlantern", "Joseph", "Harro", "DC", "male", "green", "black"),
    ("earth3aquaman", "Arthur", "Curry", "DC", "male", "green", "gold"),
    ("earth3cyborg", "Victor", "Stone", "DC", "male", "gray", "red"),
    ("earth3greenarrow", "Oliver", "Queen", "DC", "male", "green", "black"),
    ("earth3catwoman", "Selina", "Kyle", "DC", "female", "black", "purple"),
    ("earth3joker", "Jack", "Napier", "DC", "male", "purple", "green"),
    # More Fatal Five / Legion foes
    ("fatalvalidus", "Validus", "Bismoll", "DC", "male", "gray", "red"),
    ("fatalemerald", "Sarya", "Vandu", "DC", "female", "green", "gold"),
    ("fatalmano", "Mano", "Yald", "DC", "male", "purple", "black"),
    ("fataltharok", "Tharok", "Nolan", "DC", "male", "green", "gray"),
    ("fatalpersuader", "Cole", "Parker", "DC", "male", "silver", "black"),
    ("fatalcaress", "Cinta", "Prounis", "DC", "female", "pink", "black"),
    ("fatalmentalla", "Mia", "Dubois", "DC", "female", "purple", "white"),
    ("fatalflare", "Ki", "Assam", "DC", "female", "orange", "yellow"),
    ("computo", "Computo", "Legion", "DC", "male", "green", "silver"),
    ("darkseidlegion", "Uxas", "Darkseid", "DC", "male", "gray", "blue"),
    ("glorith", "Glorith", "Legion", "DC", "female", "purple", "gold"),
    ("time trapper", "Time", "Trapper", "DC", "male", "purple", "black"),
    # Additional Lanterns / corps members
    ("abinsur", "Abin", "Sur", "DC", "male", "blue", "black"),
    ("tomar tu", "Tomar", "Tu", "DC", "male", "blue", "brown"),
    ("laragand", "Lara", "Gand", "DC", "female", "green", "black"),
    ("keithkenyon", "Keith", "Kenyon", "DC", "male", "green", "brown"),
    ("jackt chance", "Jack", "Chance", "DC", "male", "green", "blond"),
    ("rotlapp", "Rot", "Lapp", "DC", "male", "green", "brown"),
    ("pathavim", "Path", "Avim", "DC", "male", "green", "black"),
    ("reeg", "Reeg", "Broon", "DC", "male", "green", "brown"),
    ("morro", "Morro", "Lantern", "DC", "male", "green", "black"),
    ("probert", "Probert", "Lantern", "DC", "male", "green", "brown"),
    ("chaselon", "Chaselon", "Lantern", "DC", "male", "green", "black"),
    ("larox", "Larox", "Lantern", "DC", "male", "green", "brown"),
    ("ganthet", "Ganthet", "Guardian", "DC", "male", "blue", "white"),
    ("sayd", "Sayd", "Guardian", "DC", "female", "blue", "white"),
    ("appaa ali apsa", "Appa", "Ali", "DC", "male", "blue", "white"),
    ("krona", "Krona", "Maltus", "DC", "male", "blue", "white"),
    ("yellowfear", "Parallax", "Fear", "DC", "male", "yellow", "green"),
    ("ionentity", "Ion", "Entity", "DC", "male", "green", "white"),
    ("parallaxentity", "Parallax", "Entity", "DC", "male", "yellow", "green"),
    ("ophidian", "Ophidian", "Entity", "DC", "male", "orange", "yellow"),
    ("butcherentity", "Butcher", "Entity", "DC", "male", "red", "black"),
    ("proselyte", "Proselyte", "Entity", "DC", "female", "indigo", "white"),
    ("predator", "Predator", "Entity", "DC", "male", "violet", "black"),
    ("nemesis", "Nemesis", "Entity", "DC", "female", "black", "white"),
    ("lifeentity", "Life", "Entity", "DC", "female", "white", "gold"),
]


def prefixed_replacement_heroes() -> list[tuple[str, str, str, str, str | None, str | None, str | None]]:
    """Return replacement heroes with group-prefixed usernames to avoid collisions."""
    group_prefixes = (
        "ss",
        "cs",
        "ff",
        "gl",
        "yl",
        "rl",
        "ol",
        "bl",
        "in",
        "vl",
        "bk",
        "wh",
    )
    rows: list[tuple[str, str, str, str, str | None, str | None, str | None]] = []
    for index, (codename, first, last, publisher, sex, color1, color2) in enumerate(
        REPLACEMENT_DC_HEROES
    ):
        prefix = group_prefixes[index % len(group_prefixes)]
        base = "".join(ch for ch in codename.lower() if ch.isalnum())[:56]
        username = f"{prefix}{base}"
        rows.append((username, first, last, publisher, sex, color1, color2))
    return rows
